### ISSUE TITLE
Migration to Tensorflow 2 and tf.keras

### ISSUE THREAD

**Issue by deepgradient** [danielegrattarola/spektral#10]
Hi,
Thanks for your great work.

Could you please support Tensorflow 2 for Spektral?

**Comment by danielegrattarola** [comment]
Hi,

Support for TF2 will come eventually, I still haven't started looking into it.
Do you have some specific requests about it?

Cheers

**Comment by deepgradient** [comment]
Thanks for getting back to me.
I need all algorithms to be run in TF2.

How long may it take?

**Comment by danielegrattarola** [comment]
Unfortunately I cannot give definitive timeline for porting the framework to tf2/tf.keras, sorry.

**Comment by cgarciae** [comment]
Can we leave this issue open? I think that we could start a branch and migrate little by little.

**Comment by danielegrattarola** [comment]
Yeah, I was using #12 to post updates about the TF2 situation but here is probably better. 

I have already started some development for migrating to TF2, it's still a bit early to push. 
I have been a bit busy recently, but I'll resume working on Spektral soon and hopefully we can have a proper TF2/tf.keras release soon, I hope before the end of the month.

**Comment by cgarciae** [comment]
Nice! I've been posting on some of the tensorflow issues + mailing list to see if they can give some priority to this :)

**Comment by danielegrattarola** [comment]
@cgarciae So I went back and looked at what I had done before the holiday break, and apparently most of the work was already there. 

I have created the `tf2` branch and pushed it. All tests pass on my machine, currently running them on Travis to make sure. 
It'll probably take some time before every bug is ironed out, but for now it can be a good starting point for TF2 users.

**Comment by danielegrattarola** [comment]
The `tf2` branch was merged into `develop`. 
TF2 users should pull the latest changes and switch to that branch for receiving updates.

**Comment by cgarciae** [comment]
Nice!

**Comment by danielegrattarola** [comment]
PSA: starting from v0.3.0, the `develop` branch was merged to `master` and now Spektral primarily supports Tensorflow 2 and `tf.keras`. All future releases will only support Tensorflow 2. 
The old version of Spektral (0.1.0), which is based on TensorFlow 1.15 and Keras 2.2.5, has been moved to the `tf1` branch and will only be updated with bugfixes. 

I will be closing this issue because it's solved. Feel free to dm me any questions. 

Cheers
