### ISSUE TITLE
Do examples run on GPU by default?

### ISSUE THREAD

**Issue by msaroufim** [danielegrattarola/spektral#100]
I know that Keras models are ran by default on GPU if the device is available

```
tf.test.gpu_device_name()
/device:GPU:0
```

But I was wondering if this plays well with the custom training loop you have in the examples

I don't see a significant difference in GPU vs CPU training time if I just change the hardware accelator in setting in Collab https://colab.research.google.com/drive/1D3VZwCQ6Naw38n19XuZJbJTKxEgQ3hwU?usp=sharing

Would really appreciate pointers in the right direction, I'm happy to submit any possible improvements back to the examples

**Comment by msaroufim** [comment]
Just bugs in my code sorry for spam

**Comment by danielegrattarola** [comment]
No worries, I'm glad that it worked out.
Cheers
