### ISSUE TITLE
Using your own data

### ISSUE THREAD

**Issue by IsmailAlaouiAbdellaoui** [danielegrattarola/spektral#101]
If I want to experiment things with my own data ( synthetic graph ), how can I proceed ?
Thanks.

**Comment by danielegrattarola** [comment]
Depending on the data, you need a sparse adjacency matrix (or many adjacency matrices, if you have many graphs) and a matrix of node features (or many matrices of node features). 
Then, any of the examples should work out of the box with your new data. 

Cheers

**Comment by IsmailAlaouiAbdellaoui** [comment]
Thanks for the reply, I will try with my own matrices.

Cheers !
