### ISSUE TITLE
Loading saved model in mixed mode

### ISSUE THREAD

**Issue by reallsx** [danielegrattarola/spektral#105]
Hi there,

I followed the [example](https://github.com/danielegrattarola/spektral/blob/master/examples/other/graph_signal_classification_mnist.py) of graph signal classification to build a GCN of similar structure and it did well. Then I saved the model using `model.save('./GCN_model.h5')` and  loaded the model in another notebook with `model = keras.models.load_model('./GCN_model.h5', custom_objects = {'GraphConv' : GraphConv})`. This time the model requires two input unlike in the example and the time it was trained. The error message is pasted below.

I also tried to put the adjacency matrix in different form along with the data in a list and use that as a input but it still doesn't work. Is there any existing solution to load a model build in mixed mode and make it behaves as the same when it was trained?

```
pred = model.predict(data)

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-22-77e35d647a61> in <module>
----> 1 pred = model.predict(data)

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in predict(self, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing)
   1011         max_queue_size=max_queue_size,
   1012         workers=workers,
-> 1013         use_multiprocessing=use_multiprocessing)
   1014 
   1015   def reset_metrics(self):

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in predict(self, model, x, batch_size, verbose, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    496         model, ModeKeys.PREDICT, x=x, batch_size=batch_size, verbose=verbose,
    497         steps=steps, callbacks=callbacks, max_queue_size=max_queue_size,
--> 498         workers=workers, use_multiprocessing=use_multiprocessing, **kwargs)
    499 
    500 

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in _model_iteration(self, model, mode, x, y, batch_size, verbose, sample_weight, steps, callbacks, max_queue_size, workers, use_multiprocessing, **kwargs)
    424           max_queue_size=max_queue_size,
    425           workers=workers,
--> 426           use_multiprocessing=use_multiprocessing)
    427       total_samples = _get_total_number_of_samples(adapter)
    428       use_sample = total_samples is not None

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py in _process_inputs(model, mode, x, y, batch_size, epochs, sample_weights, class_weights, shuffle, steps, distribution_strategy, max_queue_size, workers, use_multiprocessing)
    644     standardize_function = None
    645     x, y, sample_weights = standardize(
--> 646         x, y, sample_weight=sample_weights)
    647   elif adapter_cls is data_adapter.ListsOfScalarsDataAdapter:
    648     standardize_function = standardize

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, batch_size, check_steps, steps_name, steps, validation_split, shuffle, extract_tensors_from_dataset)
   2381         is_dataset=is_dataset,
   2382         class_weight=class_weight,
-> 2383         batch_size=batch_size)
   2384 
   2385   def _standardize_tensors(self, x, y, sample_weight, run_eagerly, dict_inputs,

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py in _standardize_tensors(self, x, y, sample_weight, run_eagerly, dict_inputs, is_dataset, class_weight, batch_size)
   2408           feed_input_shapes,
   2409           check_batch_axis=False,  # Don't enforce the batch size.
-> 2410           exception_prefix='input')
   2411 
   2412     # Get typespecs for the input data and sanitize it if necessary.

~/.conda/envs/my_strax/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_utils.py in standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    537                        'for inputs ' + str(names) + ' but instead got the '
    538                        'following list of ' + str(len(data)) + ' arrays: ' +
--> 539                        str(data)[:200] + '...')
    540     elif len(names) > 1:
    541       raise ValueError('Error when checking model ' + exception_prefix +

ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), for inputs ['input_11', 'input_12'] but instead got the following list of 1 arrays: [array([[[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.        ],
        [0.        ],
        [0.        ]],

       [[0.        ],
        [0.0005883 ],
        ...
```

**Comment by danielegrattarola** [comment]
Hi, 

it may be hard to save and load the model from that particular example because the input tensor `A_in` is provided as a "static" input to the model and is likely not saved when calling `model.save`. 
A quick fix would be to write your own training loop (similar to [this one](https://github.com/danielegrattarola/spektral/blob/master/examples/node_prediction/citation_gcn_fast.py)) and feed matrix `fltr` as input every time.
 
That example is seriously outdated anyway, I will fix it to be more suitable for Tensorflow 2 soon.

Cheers, 
Daniele

**Comment by danielegrattarola** [comment]
Check out the updated example (commit 130353e6370790549fb7a8edf19f2d0615fb3588). 
It should fix this issue.

Cheers

**Comment by reallsx** [comment]
Thanks for the update. I figured out that I can follow the old example and save the weights of trained network, and then load the weights into a new constructed GCN with the same structure when I want to use it. Using a "static" input really make the network fast and I want to keep the speed.

The new example looks much less Keras-ish. I have some trouble making it to work with my data. Haven't figured out what's wrong.

It would be so much more convenient if I could save the entire network with the "static" input. Maybe I should open a issue at the Keras/TensorFlow repo.

**Comment by danielegrattarola** [comment]
I agree that it looks less Keras-ish, but at the same time it is more like the new TF2-style of doing things. 
Your solution also looks good, although you have to exactly re-define the model when you load it which may be tedious.

Let me know if you need help with getting the new example to work with your data. 
Cheers
