### ISSUE TITLE
Graph classification on graphs with identical adjacency matrices

### ISSUE THREAD

**Issue by Florisvdf** [danielegrattarola/spektral#106]
Hi,

I would like to create a model capable of classifying graphs where each graph shares the same adjacency matrix. I have a relatively large number of nodes (800 or so) and I think I'm encountering issues with memory overflow (my kernel crashes when I call model.fit). Is it possible to pass a single adjacency matrix to the model, instead of passing batches of identical matrices? Or is there another memory efficient way of dealing with this?

**Comment by danielegrattarola** [comment]
Hi, 

have you taken a look at [mixed mode](https://graphneural.network/data/#mixed-mode) data representation?
There is also a [template example](https://github.com/danielegrattarola/spektral/blob/master/examples/other/graph_signal_classification_mnist.py) to get you started. 

Cheers

**Comment by Florisvdf** [comment]
Hi Daniele,

Thanks for your swift reply. I'm in the process of creating an Edge Conditioned CNN and I was under the impression that mixed mode was not supported for this type of model. 
Either way, I've been trying to create a sparse adjacency matrix like how it's done in the MNIST example:
`fltr = GraphConv.preprocess(A)
fltr = sp_matrix_to_sp_tensor(fltr)`

I have a node matrix of shape (n_samples, n_nodes, n_node_features) and an edge matrix of shape (n_samples, n_nodes, n_nodes, n_edge_features).
Passing a batch of nodes, the sparse adjacency matrix (fltr) and a batch of edges to the ECC layer results in an error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-8cf4dcfabd5c> in <module>
    121 
    122     # Training step
--> 123     l, a = train(*batch)
    124     results_tr.append((l, a))
    125 

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    821       # This is the first call of __call__, so we have to initialize.
    822       initializers = []
--> 823       self._initialize(args, kwds, add_initializers_to=initializers)
    824     finally:
    825       # At this point we know that the initialization is complete (or less

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    694     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    695     self._concrete_stateful_fn = (
--> 696         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    697             *args, **kwds))
    698 

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2853       args, kwargs = None, None
   2854     with self._lock:
-> 2855       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2856     return graph_function
   2857 

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3211 
   3212       self._function_cache.missed.add(call_context_key)
-> 3213       graph_function = self._create_graph_function(args, kwargs)
   3214       self._function_cache.primary[cache_key] = graph_function
   3215       return graph_function, args, kwargs

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3063     arg_names = base_arg_names + missing_arg_names
   3064     graph_function = ConcreteFunction(
-> 3065         func_graph_module.func_graph_from_py_func(
   3066             self._name,
   3067             self._python_function,

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    984         _, original_func = tf_decorator.unwrap(python_func)
    985 
--> 986       func_outputs = python_func(*func_args, **func_kwargs)
    987 
    988       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    598         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    599         # the function a weak reference to itself to avoid a reference cycle.
--> 600         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    601     weak_wrapped_fn = weakref.ref(wrapped_fn)
    602 

~/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

ValueError: in user code:

    <ipython-input-6-d2ac8c2b1873>:86 train  *
        predictions = model([x, fltr, E], training=True)
    <ipython-input-7-8cf4dcfabd5c>:65 call  *
        x = self.conv1([x, fltr, E])
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/spektral/layers/convolutional/ecc_conv.py:147 call  *
        kernel = K.reshape(kernel_network, target_shape)
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/keras/backend.py:2911 reshape
        return array_ops.reshape(x, shape)
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py:195 reshape
        result = gen_array_ops.reshape(tensor, shape, name)
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py:8233 reshape
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:742 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:591 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3477 _create_op_internal
        ret = Operation(
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1974 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home/florisvdf/miniconda3/envs/spektral/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1815 _create_c_op
        raise ValueError(str(e))

    ValueError: Cannot reshape a tensor with 1837056 elements to shape [897,897,32,2] (51494976 elements) for '{{node net_4/edge_conditioned_conv_4/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](net_4/edge_conditioned_conv_4/FGN_out/BiasAdd, net_4/edge_conditioned_conv_4/Reshape/shape)' with input shapes: [32,897,64], [4] and with input tensors computed as partial shapes: input[1] = [897,897,32,2].


Could this be the result of the ECC not supporting mixed mode yet?

**Comment by danielegrattarola** [comment]
You are correct, mixed mode is not supported for ECC and the error is due to that. 
I think you are stuck with duplicating the adjacency matrix, for now, I've tried to get mixed mode working with ECC but with no success so far.

**Comment by Florisvdf** [comment]
Ok, thanks for clearing that up! 
Cheers
