### ISSUE TITLE
Huge ram just for normalizing graph!

### ISSUE THREAD

**Issue by Keramatfar** [danielegrattarola/spektral#110]
Thanks for your package,
I am using spektral for a 11000 nodes graph, and it keeps to crashing for ram in a 13 GB system. I investigated the issue and found the following line as a bottleneck, because it just start to filling memory on this line and after it the memory gets free.

fltr1 = GraphConv.preprocess(A).astype('f4')

Why is it like this?

**Comment by Keramatfar** [comment]
I handled this by sparse matrix input.

**Comment by danielegrattarola** [comment]
Hi, 

yes, that would have been my suggestion. 

I am working on improving the memory efficiency of some normalization operations, but some of them will still need to copy the matrix. 

Cheers
