### ISSUE TITLE
Are GATs permutation invariant?

### ISSUE THREAD

**Issue by pnxenopoulos** [danielegrattarola/spektral#114]
If I change the ordering of the input nodes, along with their associated edges in the adjacency matrix, should I expect a different output? 

Using the example for graph classification ([https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/delaunay_batch.py](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/delaunay_batch.py))

I created a single observation where I'd rearrange the nodes in a graph and its corresponding adjacency matrix:

```
X_t = X[0]
A_t = A[0]

new_X_t = np.vstack([X_t[4:,:], X_t[0:4,:]])
new_A_t = np.vstack([A_t[4:,:], A_t[0:4,:]])
```

Then, after running `predict` on the trained model, I get two differing outputs, even though I believe I only rearranged the node ordering in the input.

Input:
`model.predict([X_t.reshape(-1, 7, 2), A_t.reshape(-1, 7, 7)])`
Output:
`array([[0.7369365, 0.2630635]], dtype=float32)`

Input:
`model.predict([new_X_t.reshape(-1, 7, 2), new_A_t.reshape(-1, 7, 7)])`
Output:
`array([[0.74314904, 0.25685093]], dtype=float32)`

Close, but ultimately differing results. Are GATs not permutation invariant?

**Comment by danielegrattarola** [comment]
Hi, 

GATs are permutation *equivariant* and a model equipped with GATs and global pooling is invariant. 
If I'm reading this correctly:
```
new_A_t = np.vstack([A_t[4:,:], A_t[0:4,:]])
```
then you're shuffling the rows of the adjacency matrix but not the columns. 
Can you try shuffling the columns as well and report the results?

Cheers

**Comment by pnxenopoulos** [comment]
Ah yes, I see my error. After shuffling the columns, that fixed it. Thank you!

**Comment by danielegrattarola** [comment]
Good luck with your project!!
