### ISSUE TITLE
Feature Request: Conv layer that updates E instead of X

### ISSUE THREAD

**Issue by JackMaguire** [danielegrattarola/spektral#117]
Hi Daniele - feel free to disregard completely this but I saw a neat technique in [this paper (Fig 1)](https://www.biorxiv.org/content/10.1101/868935v2.full.pdf) where their edges are updated between traditional GCN layers. It would be really neat to have something like this in Spektral, though I have no idea how much work this would be. Is this of any interest?

**Comment by JackMaguire** [comment]
![Screen Shot 2020-11-19 at 12 57 16 PM](https://user-images.githubusercontent.com/15745488/99704715-c2503800-2a66-11eb-9521-ae05e1bef41d.png)

(The figure in question)

**Comment by danielegrattarola** [comment]
Hi Jack,

that looks doable, I will put it in the pipeline so that maybe it can be in the upcoming 1.0 release. 
Thanks for bringing this to my attention!

Cheers, 
Daniele

**Comment by JackMaguire** [comment]
Congrats on v1.0!! 🎉

**Comment by danielegrattarola** [comment]
@JackMaguire thanks!! 

Btw I have not forgotten about this FR, it will be part of the next minor release which should add 10 or so new layers :D

**Comment by JackMaguire** [comment]
> 10 or so new layers

I'm very excited! The data management tools look incredibly useful, too.

**Comment by JackMaguire** [comment]
I think it's safe to close this :)
