### ISSUE TITLE
Extract features from pre-trained model.

### ISSUE THREAD

**Issue by dimmykarson** [danielegrattarola/spektral#118]
Hi, thanks for the great package!

I'm trying to extract the features from the last layer of my model. I had done this before but with spektral it doesn't work.
Given a GCN model with 3 layers (GraphConv ~ GraphConv_1 ~ GraphConv_2, the last being a layer with softmax) I am trying to obtain the output matrix of the GraphConv ~ 1 layer:

`import keras.backend as K

get_last_layer_output = K.function([model.inputs, [model.layers[-2].output])

features = get_last_layer_output([X])`

My model is:
input_1 [(None, 50)]   (InputLayer)  (features)                       
input_2 [(None, 19)] (InputLayer) (adjacency matrix)                                
graph_conv (None, 128) (GraphConv)                    
graph_conv_1 (None, 64) (GraphConv)     
graph_conv_2 (None, 2)(GraphConv)       
`

The error:

`Traceback (most recent call last):
 _run_internal_graph
    assert x_id in tensor_dict, 'Could not compute output ' + str(x)
AssertionError: Could not compute output Tensor("graph_conv_1/Relu:0", shape=(None, 64), dtype=float32)
`

**Comment by danielegrattarola** [comment]
Hi, 

you are giving `X` as input to `get_last_layer_output`, but not `A`. Is that intentional?
Otherwise, I would need a working code snippet to reproduce the issue, can you link it here?

Cheers
