### ISSUE TITLE
Top-K pooling without a dense matrix

### ISSUE THREAD

**Issue by cruyffturn** [danielegrattarola/spektral#124]
In the description of Top-K pooling it's stated that:

> This layer temporarily makes the adjacency matrix dense in order to compute A′.

Can there be a way of working directly with the sparse matrix? Because I'm working with a dataset where the dense matrix doesn't fit the GPU.

Thank you.

**Comment by danielegrattarola** [comment]
Hi, 

that's a very reasonable request and I have indeed been working on improving the pooling layers. 
Unfortunately the code is not ready to be released just yet, I hope to get it into v1.1 which should happen early in January. 

Can you use either MinCutPool or DiffPool for now? 
Sorry for the inconvenience.

Cheers

**Comment by cruyffturn** [comment]
Thank you. If you need any help about testing, I can try my best.

**Comment by danielegrattarola** [comment]
This was solved in 4746108.

**Comment by cruyffturn** [comment]
Thank you!
