### ISSUE TITLE
condition "if step == loader_tr.steps_per_epoch"  always true in graph_signal_classification_mnist.py

### ISSUE THREAD

**Issue by phupe** [danielegrattarola/spektral#126]
In the example from the file `graph_signal_classification_mnist.py`, the condition `if step == loader_tr.steps_per_epoch` is always true. 

From the Loader class, the `steps_per_epoch` is computed like this:
```
    @property
    def steps_per_epoch(self):
        return int(np.ceil(len(self.dataset) / self.batch_size))
```

But when the `PackedBatchLoader` class is used, the dataset is packed and I guess that `len(self.dataset)` is 1, and so is `steps_per_epoch`.

I thing the condition `if step == loader_tr.steps_per_epoch` should be replaced by something else.

Don't you think that the `for batch in loader_tr:` should be replaced by something like:

```
step = 0
for epoch in range(epochs):
    step += 1

     for batch in loader_tr:
              model.train_on_batch

     if (step % some_value) == 0:
              evaluate
              .....

```

Thanks

**Comment by danielegrattarola** [comment]
Hi,

that's 100% a bug in the loader, thanks for noticing. 
I will push a hotfix to PyPi shortly. 

Cheers
