### ISSUE TITLE
Error in add_self_loops 

### ISSUE THREAD

**Issue by agoldin** [danielegrattarola/spektral#137]
in spektral/layers/ops/sparse.py

Example:
n_nodes=55
inp_lap = layers.Input((n_nodes, ), 
                           sparse=True,
                           dtype=tf.float32, batch_size = n_nodes)
xx = layers.Input((5,))
ll = GraphSageConv(32,input_shape=(n_nodes,5))
ll([xx,inp_lap])

Error:
 ValueError: Number of mask dimensions must be specified, even if some dimensions are None.  E.g. shape=[None] is ok, but shape=None is not

in this line:
indices_od = indices[mask_od]

tf.__version__
'2.2.0'

spektral.__version__
'1.0.2'

What am I doing wrong?

Thanks!!

**Comment by danielegrattarola** [comment]
Hi, 

the problem is with TensorFlow 2.2, I realized I never tested the library with your config. 
I will push a fix shortly and update the package on PyPi.

You can install from source or update TF to 2.3 for now. 

Thanks for spotting the bug.
Cheers

**Comment by agoldin** [comment]
Thanks!
