### ISSUE TITLE
Loader iteration speed is very dependent of dataset size

### ISSUE THREAD

**Issue by adelabriere** [danielegrattarola/spektral#139]
Dear Daniele,

Thanks for the amazing work, as a non machine learning person it is amazing to be able to use graph neural network in a user firendly manner, I work on small biological molecules and this seems to be a very promising tool for my applications.

I encountered a dicrepancy in speed that I can t really explain at the moment. The iteration time using a DisjointLoader is not linear at all, for the same batch size (32) on my computer I obtained:
- Subset of size 1000 of QM9 : 12ms by batch
- Subset of size 5000 of QM9 : 35ms by batch
- Subset of size 10000 of QM9 :  84ms by batch

From my understanding, it should not be happening. I am still trying to understand from where in the code this is coming from. If you have any clue to speed this up it would be super useful, as it is a limiting factor on my real dataset.

Here is the code that I used to evaluate this:
```
from spektral.data import DisjointLoader
from spektral.datasets import QM9
from tqdm import tqdm
import time

epochs = 2          # Number of training epochs
batch_size = 32       # Batch size

dataset = QM9(amount=1000)
medium_dataset = QM9(amount=5000)
long_dataset = QM9(amount=10000)

# Parameters
F = dataset.n_node_features  # Dimension of node features
S = dataset.n_edge_features  # Dimension of edge features
n_out = dataset.n_labels     # Dimension of the target

# We check if everything is similar
F_long = long_dataset.n_node_features  # Dimension of node features
S_long = long_dataset.n_edge_features  # Dimension of edge features
n_out_long = long_dataset.n_labels


print(F,S,n_out)
print(F_large,S_large,n_out_large)


# Loader building
loader = DisjointLoader(dataset, batch_size=batch_size, epochs=epochs)
medium_loader = DisjointLoader(medium_dataset, batch_size=batch_size, epochs=epochs)
long_loader = DisjointLoader(long_dataset, batch_size=batch_size, epochs=epochs)

# Loader building
t_start_small = time.process_time()
for batch in tqdm(loader):
    continue
t_stop_small = time.process_time()
t_iter_small = (t_stop_small-t_start_small)/loader.steps_per_epoch

t_start_medium = time.process_time()
for batch in tqdm(medium_loader):
    continue
t_stop_medium = time.process_time()
t_iter_medium = (t_stop_medium-t_start_medium)/medium_loader.steps_per_epoch

t_start_long = time.process_time()
for batch in tqdm(long_loader):
    continue
t_stop_long = time.process_time()
t_iter_long = (t_stop_long-t_start_long)/long_loader.steps_per_epoch

print("small:",t_iter_small," ","medium:",t_iter_medium," ","long:",t_iter_long," ")

```
Thanks,

Alexis

**Comment by danielegrattarola** [comment]
Very nice catch!! It turns out that this was an issue with the Dataset class, which had an inefficiency in computing the number of nodes, features, etc, and made it unsuitable to read these properties in a loop.

I have fixed it and now I get a consistent 7-8 microseconds per batch. You can try to install from source and see whether it works for you as well.

Cheers!

**Comment by adelabriere** [comment]
Thanks, I can confirm that it is solved and works as expected on my side !
