### ISSUE TITLE
keras version

### ISSUE THREAD

**Issue by xhtian95** [danielegrattarola/spektral#14]
Thank you very much for developing the graph neural network implemented by keras. Is GAT code used for node classification and graph classification stable? If I want to use your API, what is the limitation of keras version? Have you changed your code to tf.keras?

**Comment by danielegrattarola** [comment]
Hi, 

>Is GAT code used for node classification and graph classification stable? 
It hasn't changed in a while now, I'd consider it stable.

>If I want to use your API, what is the limitation of keras version? 
2.2.5 currently, because 2.3 has issues with sparse inputs (see #12 )

>Have you changed your code to tf.keras?
No, the current version of tf.keras has the same issues as Keras 2.3.
