### ISSUE TITLE
loader signature is wrong when called multiple times

### ISSUE THREAD

**Issue by adelabriere** [danielegrattarola/spektral#140]
Hi again,

I guess the bug was introduced by the fix that you did this morning, but the output tf_signature on disjoint loader change when called multiple times, everytime a None is added at the beginning of the TensorSpec:
```
from spektral.data import DisjointLoader
from spektral.datasets import QM9

epochs = 2          # Number of training epochs
batch_size = 32       # Batch size

dataset = QM9(amount=1000)
loader = DisjointLoader(dataset, batch_size=batch_size, epochs=epochs)
sign1 = loader.tf_signature()
sign2  =loader.tf_signature()
sign1[1] TensorSpec(shape=(None, 19), dtype=tf.float64, name=None)
sign2[1] TensorSpec(shape=(None, None, 19), dtype=tf.float64, name=None)
```
Best,
Alexis

**Comment by danielegrattarola** [comment]
You are right, I pushed the fix quickly this morning without realizing the implications. I think I need to write a proper cache management system for the dataset class, I'll let you know when this is fixed.

Thanks again

**Comment by danielegrattarola** [comment]
This should fix both issue, can you try it now?

Thanks, 
Daniele

**Comment by adelabriere** [comment]
It works for me now, 

Thanks !
