### ISSUE TITLE
Contributions Proposal

### ISSUE THREAD

**Issue by jackd** [danielegrattarola/spektral#148]
I've recently started looking at GNNs and wanted to build myself a decent benchmarking suite. Having found this repo (which is awesome - nice work!) I'm thinking it might be more productive for me to contribute here rather than going down my own route (to be honest I'll probably do a hybrid approach - start my own repo and push useful stuff that's wanted upstream here). Having said that, I appreciate contributions need to be reviewed and we may have differing priorities.

I thought I'd suggest a bunch of things I'm keen to do and am happy to contribute here, and give you the opportunity to prioritized/shoot down any before I invest too much effort. For those that are wanted, I'm also happy to take guidance on the manner in which to go about them.

A lot of the suggestions are highly subjective - please consider those as "if this was my project, I'd do xyz" rather than me trying to force my preferences onto the project. They're mostly things I'll be doing for my own sake anyway - it's just a question of whether they're wanted here.

I'm happy to open separate issues for any that need extensive discussion, but maybe I'll let you shoot down any before I go to that effort.

## Code "cleanliness"

This is the most subjective - and to be clear, I think the existing code base is very clean. There are a few things I would consider "icing on the cake" that I've liked in other projects. In particular:

- [pre-commit](https://pre-commit.com/) config / README instructions? Would currently only run flake8 check (I could add [autoflake](https://pypi.org/project/autoflake/?)
- optional type hints (with or without CI check / tests)
- formatter? [black](https://black.readthedocs.io/en/stable/) or [yapf](https://github.com/google/yapf)? The only opinion I hold when it comes to formatting is that having a formatter that removes my need for an opinion is good.
- [isort](https://github.com/PyCQA/isort)

I'm happy to set up CI checks (and/or pre-commit configs) for any/all of those that are desired.

## Example CLIs

This should make examples easier to run in workflows - no more `sed`ing - and make model benchmarking (see below) easier.

## Expand Models

Most of the examples have duplicated model definitions. I think a uniform interface for constructing these under `spektral/models` would be beneficial. Something like

```python
def gcn_model(input_spec, output_spec, **kwargs) -> tf.keras.Model:
   ...
```

where `input_spec` and `output_spec` are possibly nested structures of `[Sparse|Ragged]?TensorSpec`s.

## Models Benchmarks

The main draw card of this repo for me is implementations of existing models - but some aren't producing the same results as those reported in their respective papers. I understanding sorting through the fine details isn't much fun, and an approximate re-implementation is definitely better than nothing - but it would be nice to know at a glance how confident we are that an implementation presented here is consistent with the original paper, and roughly how long training a model should take.

This would probably be too expensive to integrate with CI, but in the short term perhaps a directory with a bunch of short bash scripts which utilize example CLIs discussed above and a `README` that summarized the results would suffice? Perhaps some automatically generated tables with major releases that show performance across versions.

## Operation Benchmarks

Similar to model benchmarks, but focusing on computational efficiencies of different implementations. I know people have their opinions about what constitutes premature optimization, but I get disproportionately annoyed using that I know could be implemented faster...

Futher down the line, automatically generated reports would be nice to monitor for performance regressions between versions.

## tf.data.Dataset Pipeline

I'm not going to lie - I don't understand the motivation behind the spektral `Dataset` and `Loader` classes. Compared to `tf.data.Dataset`s there's a massive overlap. From what I can tell, the key differences are `spektral` supports:

- numpy/scipy `Graph` elements;
- batching with numpy; and
- indexed-based access.

`tf.data.Dataset`s support:

- lazy iteration / mapping (with `cache`ing for expensive operations)
- parallel mapping
- checkpointable iterators
- potential immutability

`tf.data.Dataset`s are used elsewhere and would lower the learning curve for people familiar with tensorflow. There are some tricks with batching (that are a lot easier now that `tf.data.experimental.dense_to_ragged_batch` exists), but having been through the process on a number of different projects now I'm confident the `tf.data.Dataset` API can handle 99% of cases (and for the few issues remaining I'd rather make some noise in tensorflow issues).

I understand this would be quite a big change, but I'll likely do it for my own projects anyway - perhaps I could prototype elsewhere and present some completed examples.

**Comment by danielegrattarola** [comment]
Hi, 

first of all, thanks for having taken an interest in the project and I really appreciate your offer for support. 

I will give you some off-the-top-of-my-head replies to all points, but it would be cool to hear your opinion so don't take these as definitive answers. 

## Code "cleanliness"

I never used any of the tools that you mentioned and I would be happy to learn. 

The current workflow simply runs `pytest` and `codecov` via TravisCI and a subset of the example scripts via GH Actions. 
The code style I use is PEP8 with auto-formatting done by PyCharm. 

I am open to adding more automated tests, formatting, etc, although I am not familiar with best practices in this regards. 
Black seems like a good alternative to standard PEP8. Type hints are definitely good to have, although they are not present in TF/Keras (this is also something that I would like to maintain, although loosely: Spektral's style should be similar to Keras'). 

## Example CLIs

The current setup is just me being lazy :D The `sed` based workflow was pushed by a user some time ago and I never got around to cleaning it up. 
I agree that it is time to move to argparse or similar.

## Models

Expanding `spektral/models` is currently one of the top priorities, along with `spektral/layers`. It would be great to have a collection of models implemented with Model subclassing, making them modular enough to be usable in all experiment of a given type (e.g., node classification). 
(I like your idea of giving the input and output typespecs, but I consider it a more advanced feature which could be an obstacle to less savvy users).

Examples could be re-written to use these new models.
I already have the code for benchmarks (which I used for the experiments in the Spektral paper), so I think it could be a matter of

**Comment by zhuyuecai** [comment]
I just found this repo and this issue interesting. As a data engineer and data scientist in a commercial company, I would say this proposal is really important for this repo if you want to productionize it. 

If my opinion is allowed, here is my thoughts:

1, coding style check with flake8 and pylint in a CICD pipeline 
2, no need for autoformat in a CI, instead, provide a config file for black or sth. else you choose and suggest the contributor to run the autoformatting before submitting a PR. Since python is indent based language, its autoformator might create some unpredictable behavior. Moreover, the coding style check already guarantee the styles.
3, type hint is a must. It helps a developer understand what kind of input and output are expected which is critical for production level code. I think the reason why TF and Keras do not have this is because they are too old. They started at the time that type hint was not supported in Python. When this feature added to Python in 3.5, their code base already got too big to change, it's too expensive to do so. But as a relatively new project, type hint should be applied.  
4, It would be good to have an example pipeline for the users to run to verify that the installation is success.

**Comment by jackd** [comment]
Just put in formatting w/ CI + pre-commit [PR](https://github.com/danielegrattarola/spektral/pull/152).

W.r.t. typing, tensorflow has [expressed interest in typing](https://github.com/tensorflow/tensorflow/issues/12345), and other packages (e.g. [tensorflow-probability](https://github.com/tensorflow/probability), [tensorflow-datasets](https://github.com/tensorflow/datasets)) has already implemented them. I suspect it will take a while before it's sorted in tf, but when `keras` moves to a separate repo I wouldn't be surprised if getting that typed. It wouldn't have to be an all-or-nothing thing - perhaps just core methods and new work. I would have added them to my existing PRs already if it didn't break with the existing style.

I'll have a crack at some subclassed models / CI on citations examples.

P.S I have plenty of other things to work on - and I know it's Christmas :) -  so feel free to put off addressing the flood of PRs / issues. I'm patient and can find other things to distract myself with :).

**Comment by danielegrattarola** [comment]
> Just put in formatting w/ CI + pre-commit PR.

Thanks, I really appreciate it. 

I agree that typing is very useful and long due. I'll have a look into it over the next days, feel free to give suggestions/opinions on best practices (also @zhuyuecai seemed to have ideas).

> so feel free to put off addressing the flood of PRs

not a problem at all, I just might be less responsive in the following few days (or give quick replies -- not meant to be rude, but my main work tends to stack up during the holidays :D).
