### ISSUE TITLE
ValueError: Shapes (XX, 1) and (XX, XX) are incompatible

### ISSUE THREAD

**Issue by anfoss** [danielegrattarola/spektral#153]
I am having some issues in loading my own data . Specifically this is the script for creating the dataset

    class DS(Dataset):
        """
        """
        def __init__(self, X, Y, A, **kwargs):
            self.X = X
            self.Y = pd.read_csv(Y, sep="\t")['class'].to_numpy()
            self.A = A
            self.mask_tr = self.mask_va = self.mask_te = None
            super().__init__(**kwargs)

        def read(self):
            indices = np.arange(self.Y.shape[0])
            n_classes = 2

            idx_tr, idx_te, y_tr, y_te = train_test_split(
                indices, self.Y, train_size=0.5, stratify=self.Y)
            idx_va, idx_te, y_va, y_te = train_test_split(
                idx_te, y_te, train_size=0.5, stratify=y_te)

            self.mask_tr = _idx_to_mask(idx_tr, self.Y.shape[0])
            self.mask_va = _idx_to_mask(idx_va, self.Y.shape[0])
            self.mask_te = _idx_to_mask(idx_te, self.Y.shape[0])
            print(self.A.shape, self.X.shape, self.Y.shape)
            # (20379, 20379) (20379, 20379) (20379,)
            return [Graph(x=self.X, a=self.A, y=self.Y )]

And I'm using a GAT to perform node classification with two classes (0,1) following the citation dataset examples

    def model_GAT(N, F, n_out):
        # Parameters
        channels = 8           # Number of channels in each head of the first GAT layer
        n_attn_heads = 8       # Number of attention heads in first GAT layer
        dropout = 0.6          # Dropout rate for the features and adjacency matrix
        l2_reg = 2.5e-4        # L2 regularization rate
        learning_rate = 5e-3   # Learning rate
        # Model definition
        x_in = Input(shape=(F,))
        a_in = Input((N,), sparse=True)

        do_1 = Dropout(dropout)(x_in)
        gc_1 = GATConv(channels,
                       attn_heads=n_attn_heads,
                       concat_heads=True,
                       dropout_rate=dropout,
                       activation='elu',
                       kernel_regularizer=l2(l2_reg),
                       attn_kernel_regularizer=l2(l2_reg),
                       bias_regularizer=l2(l2_reg),
                       )([do_1, a_in])
        do_2 = Dropout(dropout)(gc_1)
        gc_2 = GATConv(n_out,
                       attn_heads=1,
                       concat_heads=False,
                       dropout_rate=dropout,
                       activation='softmax',
                       kernel_regularizer=l2(l2_reg),
                       attn_kernel_regularizer=l2(l2_reg),
                       bias_regularizer=l2(l2_reg),
                       )([do_2, a_in])

        # Build model
        model = Model(inputs=[x_in, a_in], outputs=gc_2)
        optimizer = Adam(lr=learning_rate)
        model.compile(optimizer=optimizer,
                      loss=CategoricalCrossentropy(reduction='sum'),
                      weighted_metrics=['acc'])
        model.summary()
        return model

    def mask_to_weights(mask):
        return mask.astype(np.float32) / np.count_nonzero(mask)

    weights_tr, weights_va, weights_te = (mask_to_weights(mask) for mask in (
          dataset.mask_tr, dataset.mask_va, dataset.mask_te))

    N = dataset.n_nodes          # Number of nodes in the graph
    F = dataset.n_node_features  # Original size of node features
    n_out = dataset.n_labels     # Number of classes
    model = model_GAT(N,F,n_out)

    epochs = 20000         # Number of training epochs
    patience = 100         # Patience for early stopping
    # Train model
    loader_tr = SingleLoader(dataset, sample_weights=weights_tr)
    loader_va = SingleLoader(dataset, sample_weights=weights_va)
    model.fit(loader_tr.load(),
              steps_per_epoch=loader_tr.steps_per_epoch,
              validation_data=loader_va.load(),
              validation_steps=loader_va.steps_per_epoch,
              epochs=epochs,
              callbacks=[EarlyStopping(patience=patience, restore_best_weights=True)])

However then I call model.fit with the following code there are couple of errors. First when calling model.summary the output layer has the wrong shape ( (None, 20379) ) instead of (None,2) and the first layer has also the wrong shape ((None, 20379)) once again instead of ((None, 20379, 20379)). 
Am I loading in the data wrong or is the format not correct? To my understanding I need to pass a adjacency matrix in the form (X,X) a label list in the form (X,) and a tensor with (X,Y) features per node.

**Comment by anfoss** [comment]
Solved, just had to add a dimension on the labels.

**Comment by danielegrattarola** [comment]
Sorry, I have been offline the last couple of days. 
Glad you solved it. 

Cheers
