### ISSUE TITLE
GCN model implementation potentially missing from pip distribution.

### ISSUE THREAD

**Issue by xnhp** [danielegrattarola/spektral#157]
Hey there,

I've just been fetching `spektral-1.0.3` from pip and noticed that 

```
from spektral.models.gcn import GCN
```

fails. 

Downloading the `.tar.gz` file [directly from here](https://pypi.org/project/spektral/#files) reveals that there is no file `gcn.py` in `spektral/models` although in the repo here on github there is one. 

Importing `GeneralGNN` works fine.

**Comment by danielegrattarola** [comment]
Hi, thanks for pointing this out. I have just pushed to PyPi v.1.0.4 which should fix this.

Cheers

**Comment by xnhp** [comment]
Awesome, thanks a lot for the quick reaction. That resolves the issue.
