### ISSUE TITLE
run example script failed in GPU mode

### ISSUE THREAD

**Issue by zhuyuecai** [danielegrattarola/spektral#158]
I tried two scripts in the example: citation_gat.py and citation_gcn.py, all failed with the same error:

`tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal:  Blas GEMM launch failed : a.shape=(2708, 1433), b.shape=(1433, 64), m=2708, n=64, k=1433
	 [[node model/gat_conv/MatMul (defined at /home/yuecai/workspace/spektral/spektral/layers/ops/matmul.py:49) ]]
	 [[model/gat_conv/concat/_20]]
  (1) Internal:  Blas GEMM launch failed : a.shape=(2708, 1433), b.shape=(1433, 64), m=2708, n=64, k=1433
	 [[node model/gat_conv/MatMul (defined at /home/yuecai/workspace/spektral/spektral/layers/ops/matmul.py:49) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_2802]

Errors may have originated from an input operation.
Input Source operations connected to node model/gat_conv/MatMul:
 model/dropout/dropout/Mul_1 (defined at citation_gat.py:83)	
 model/gat_conv/Reshape (defined at /home/yuecai/workspace/spektral/spektral/layers/convolutional/gat_conv.py:185)

Input Source operations connected to node model/gat_conv/MatMul:
 model/dropout/dropout/Mul_1 (defined at citation_gat.py:83)	
 model/gat_conv/Reshape (defined at /home/yuecai/workspace/spektral/spektral/layers/convolutional/gat_conv.py:185)

Function call stack:
train_function -> train_function
`

Not sure what is the reason.

I am using tensorflow 2.4

**Comment by danielegrattarola** [comment]
Hi, 

>Blas GEMM launch failed

this usually indicates a CUDA error, not something related to the library. Are you running this on a CPU or GPU? Are you sure that you have enough free memory for the GPU?

**Comment by zhuyuecai** [comment]
yeah, my GPU memory is not enough to run that example, I will close this issue
