### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by asd23548** [danielegrattarola/spektral#170]
Can you provide a requirment.txt to specify the environment? I have some trouble of running your examples.

**Comment by danielegrattarola** [comment]
Hi, 

dependencies are specified in [`setup.py`](https://github.com/danielegrattarola/spektral/blob/master/setup.py) and should be automatically installed when you install the library.

**Comment by asd23548** [comment]
Thanks. Seems it does not work via pip install, but I will try with setup.py.
