### ISSUE TITLE
RuntimeError when downloading 'reddit' dataset

### ISSUE THREAD

**Issue by YenHaoChen** [danielegrattarola/spektral#181]
Hello, 

I try to use the Google Colab to download the 'reddit' dataset. (Default setting with python 3.6)
It encounters a RuntimeError as attach figure.
![RuntimeError](https://user-images.githubusercontent.com/39526191/107711778-0aa17f80-6c7d-11eb-88a3-6c500593a4a3.png)

**Comment by danielegrattarola** [comment]
Hi, 

this issue should now be fixed in the latest commit on the `master` branch. 
Can you install from source and verify that it works for you on Colab?

Thanks

**Comment by YenHaoChen** [comment]
Thank you. It works!
