### ISSUE TITLE
GINConv should have batch normalization

### ISSUE THREAD

**Issue by cruyffturn** [danielegrattarola/spektral#188]
Thank you for the library and I have one minor remark.

In the original [paper](https://arxiv.org/abs/1810.00826), it's stated that:
> Batch normalization (Ioffe & Szegedy, 2015) is applied on every hidden layer.

However, on the GINConv class batch normalization is not used and there isn't an option for it. It can be customized easily to add batch norm but I just wanted to denote here.

**Comment by danielegrattarola** [comment]
Sorry, I totally missed this issue. Will push an update soon!

Cheers
