### ISSUE TITLE
pip install fails on Google Colab

### ISSUE THREAD

**Issue by jhjensen2** [danielegrattarola/spektral#19]
Here's the link to he notebook
https://colab.research.google.com/drive/1s2Mr7SG2UG8lVbk81r94_4koTjy3ajsF

The error is 
  Building wheels for collected packages: pygraphviz
  Building wheel for pygraphviz (setup.py) ... error
  ERROR: Failed building wheel for pygraphviz
  Running setup.py clean for pygraphviz
Failed to build pygraphviz
Installing collected packages: pygraphviz, spektral
    Running setup.py install for pygraphviz ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3huozh2y/pygraphviz/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3huozh2y/pygraphviz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-81ncw97y/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by danielegrattarola** [comment]
Spektral [requires Pygraphviz and its dependencies](https://danielegrattarola.github.io/spektral/#installation). In Colab, try:

```
!apt-get install graphviz libgraphviz-dev libcgraph6
!pip install spektral
```

I just tried it and it worked.

Cheers

**Comment by jhjensen2** [comment]
I see that I didn't read the instructions properly, sorry! 

One question: I see you use the Keras Functional API, but it seems that the model could also be defined sequential. Is this just a preference?  I

**Comment by danielegrattarola** [comment]
For what I know, Keras Sequential does not allow multiple inputs to a layer. Basically all layers in Spektral require to have at least the adjacency matrix (A) and node features (X) as input, so that's why I used the functional API.

**Comment by jhjensen2** [comment]
OK, makes sense. Thanks for answering my questions
