### ISSUE TITLE
Adjancency matrix input to DiffPool is documented to be binary

### ISSUE THREAD

**Issue by cruyffturn** [danielegrattarola/spektral#194]
In the [documentation](https://graphneural.network/layers/pooling/#diffpool), adjacency matrix input to DiffPool is expected to be an

> Binary adjacency matrix of shape ([batch], n_nodes, n_nodes);

Is there really a need for A to be binary? Looking at your code I couldn't figure out why it's required.

**Comment by danielegrattarola** [comment]
You are correct, there is no need for it to be binary. 
I have updated the documentation and fixed a few other issues with the docs for pooling layers.

Cheers

**Comment by cruyffturn** [comment]
Thanks.
