### ISSUE TITLE
KeyError when processing 'ogbn-mag' dataset 

### ISSUE THREAD

**Issue by YenHaoChen** [danielegrattarola/spektral#196]
Hello, 
I encounter a KeyError: 'num_nodes' when processing the 'ogbn-mag' dataset  of OGB.
Can you please help me with this?

Thank you

The following is the code and error message:
![螢幕擷取畫面 2021-03-17 092859](https://user-images.githubusercontent.com/39526191/111502721-596e8900-8703-11eb-8591-24f43cdb7118.png)
![螢幕擷取畫面 2021-03-17 092940](https://user-images.githubusercontent.com/39526191/111502748-5ecbd380-8703-11eb-979a-917334fcb131.png)

**Comment by danielegrattarola** [comment]
Hi

ogbn-mag is a heterogeneous graph with different node types and is not supported by Spektral. 
Even if this issue with the dataset was fixed, the dataset could not be used with the other features of the library. 

A solution is to create your own Dataset and Loader classes to process heterogeneous attributes.

Cheers

**Comment by YenHaoChen** [comment]
Thanks ^^
