### ISSUE TITLE
[Possible Bug] Out-of-order edge feature array in QM9 data set

### ISSUE THREAD

**Issue by MarkusFerdinandDablander** [danielegrattarola/spektral#199]
Hello and thanks for this great GNN library.

The mol_to_adj function in spektral/spektral/datasets/qm9.py puts out a numpy array called egde_attr of shape (n_edges, n_edge_features).

It seems that edges in the edge_attr array do not appear in lexicographic order but in stacked order. For example, consider an (undirected) graph with edges (0,1), (1,0), (0,2), (2,0). As far as I understand, in the edge_attr array the associated edge features would appear in the order (0,1), (1,0), (0,2), (2,0).

This seems inconsistent with the lexicographic ordering of edge lists in other parts of the code. I would have expected an ordering of (0,1), (0,2), (1,0), (2,0).

Is this a bug in the edge feature matrix construction for the QM9 data set?

More generally, what is the canonical way in Spektral to induce an order for the rows in an edge feature matrix with shape (n_edges, n_edge_features) ?

Kind regards and all the best,
Markus

**Comment by danielegrattarola** [comment]
Hi, 

yes, this is most definitely a bug and I have pushed a fix to `develop` that addresses the issue.
I will try to push an update out as soon as possible.

To answer your question. The canonical order for edge attributes is the lexicographic order given by the indices of non-zero elements of the adjacency matrix.

Thanks for noticing this
Daniele

**Comment by MarkusFerdinandDablander** [comment]
Fantastic; thanks for clarifying!

**Comment by danielegrattarola** [comment]
This is fixed in version 1.0.6, available on PyPi now. 

Thanks again
