### ISSUE TITLE
InnerProduct error

### ISSUE THREAD

**Issue by rabbit-cat** [danielegrattarola/spektral#208]
Hi,I am using tf 2.4.0 and spektral 1.0.6 doing my work,some of my code is below:

    inputs = [X,A]
    gcn1 = spektral.layers.GCNConv(512,activation='elu',kernel_regularizer=keras.regularizers.l2(l2_reg))(inputs)
    gcn2 = spektral.layers.GCNConv(256,kernel_regularizer=keras.regularizers.l2(l2_reg))([gcn1,A])
    #Dense*2
    # keras.layers.Dropout()
    Dense1 = tf.keras.layers.Dense(64,activation="relu")(gcn2)
    Dense1 = tf.keras.layers.Dropout(dropout)(Dense1)
    Dense2 = tf.keras.layers.Dense(32,activation="relu")(Dense1)
    output = spektral.layers.InnerProduct(activation='relu')(Dense2)

    #bulid model
    model1 = tf.keras.Model(inputs=[X,A],outputs=output)
    optimizer = tf.keras.optimizers.Adam(learning_rate=lr)
    model1.compile(optimizer=optimizer,loss=loss_fun,metrics='mae')
    model1.summary()

however,when i run my code ,it give a error :
ValueError: Dimensions must be equal, but are 32 and 5801 for '{{node inner_product/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](inner_product/Reshape, inner_product/Reshape_1)' with input shapes: [?,32], [5801,?]
My input X is [5801,876] and A is [5801,5801],it seems that the error occurs when run output = spektral.layers.InnerProduct(activation='relu')(Dense2),in my opinion,this operation is just do a inner product like x*x.T,and i don't konw where is wrong and how to solve it ,could you give any help to solve it? thanks a lot !

**Comment by danielegrattarola** [comment]
Hi, 

I am not able to reproduce the issue when running your code, can you post the full stack trace of the crash?

Thanks

**Comment by rabbit-cat** [comment]
thanks for your answer,my full code is :

def get_emb_model(A,X):

    N = X.shape[0]
    F = X.shape[1]
    X = Input(shape=(N,F))
    A = Input(shape=(N,N))

    #conv*2
    inputs = [X,A]
    gcn1 = GCNConv(512,activation='elu',kernel_regularizer=keras.regularizers.l2(l2_reg))(inputs)
    gcn2 = GCNConv(256,kernel_regularizer=keras.regularizers.l2(l2_reg))([gcn1,A])
    #Dense*2
    # keras.layers.Dropout()
    Dense1 = Dense(64,activation="relu")(gcn2)
    Dense1 = Dropout(dropout)(Dense1)
    Dense2 = Dense(32,activation="relu")(Dense1)
    output = InnerProduct(activation='relu')(Dense2)

    #bulid model
    model1 = Model(inputs=[X,A],outputs=output)
    optimizer = optimizers.Adam(learning_rate=lr)
    model1.compile(optimizer=optimizer,loss=loss_fun,metrics='mae')
    model1.summary()
    
    model1.fit(inputs,A,
                epochs=epochs,
                batch_size=N,
                verbose=2)
	
    return model1 
model1 = get_emb_model(train_A,train_counts)

and the error is :
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/pycharm-2020.2.3/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/usr/local/pycharm-2020.2.3/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/disk1/spektral_GCN/sktGCN.py", line 168, in <module>
    model1 = get_emb_model(train_A,train_counts)
  File "/home/disk1/spektral_GCN/sktGCN.py", line 99, in get_emb_model
    output = InnerProduct(activation='relu')(Dense2)
  File "/home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 952, in __call__
    input_list)
  File "/home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 670, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/spektral/layers/base.py:138 call  *
        output = K.dot(inputs, K.transpose(inputs))
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:1894 dot
        math_ops.matmul(xt, yt), x_shape[:-1] + y_shape[:-2] + y_shape[-1:])
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper
        return target(*args, **kwargs)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3315 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py:5550 mat_mul
        name=name)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:750 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py:592 _create_op_internal
        compute_device)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:3536 _create_op_internal
        op_def=op_def)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:2016 __init__
        control_input_ops, op_def)
    /home/disk1/miniconda3/envs/gcn/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1856 _create_c_op
        raise ValueError(str(e))
    ValueError: Dimensions must be equal, but are 32 and 5801 for '{{node inner_product/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](inner_product/Reshape, inner_product/Reshape_1)' with input shapes: [?,32], [5801,?].
Thanks

**Comment by rabbit-cat** [comment]
sorry for disturb you, i found that i made a mistake that the shape of X is actually [F,N] and i wrote [N,F].In my opinion,GCN can be simply wrote as \hat(A)XW where A is normalized laplacian matrix,so i wrote the shape of A is [N,N],X is [N,F].Now i'am confused why i should set X to [F,N].At the same time, i found that if i set the dimension of Dense2 in my test code before _InnerProduct_ to N,it runs,if not,it report a error like **_ValueError: Dimensions must be equal,_** .My test code is :
```
A = Input(shape=(N,N))
X = Input(shape=(F,))
input = [X,A]
gcn1 = GCNConv(200,activation='elu')([X,A])
gcn1 = Dropout(0.5)(gcn1)
gcn2 = GCNConv(128,activation='elu')([gcn1,A])
D2 = Dense(32,activation='relu')(gcn2)
output = InnerProduct(activation='elu',trainable=True)(D2)

model = Model(inputs=input,outputs=output)
optimizer = optimizers.Adam(learning_rate=0.01)
model.compile(metrics='mae',loss='mse',optimizer=optimizer)
model.summary()
model.fit([counts,adj],adj,verbose=2,epochs=5,batch_size=N)
```

**Comment by danielegrattarola** [comment]
Ok, I'm still not sure what's happening with the crash above, but you are correct.
The input shapes should be

```py
X = Input(shape=(F, ))
A = Input(shape=(None, ))
```

because the "batch" dimension should be implicit when declaring the inputs (and then we set it to be N when calling fit).

Cheers

**Comment by rabbit-cat** [comment]
thanks for your help
