### ISSUE TITLE
Regarding error with spektral.chem module

### ISSUE THREAD

**Issue by gaurav-tikhe** [danielegrattarola/spektral#211]
Hello Sir/Madam,
I am student of mathematical modelling and simulation and using the Spektral library for my project work. 
Based on the link below, I am trying to run the same code but while importing this "from spektral.chem import sdf_to_nx" I am getting an error saying No module named spektral.chem.

[https://www.discngine.com/blog/2020/2/26/molecular-graphs-as-input-for-neural-networks](url)

Can you please help me regarding this issue

**Comment by danielegrattarola** [comment]
Hi, 

the `chem` module is not part of Spektral anymore, and some of the functions used in that article are buggy/not fully tested.
However, the code in that example is very similar to this: https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/qm9_ecc.py

Try and see if you can adapt this example to your use case.
Cheers

**Comment by danielegrattarola** [comment]
There is `spektral.utils.io` that has a `load_sdf` function to read an SDF file, but it is undocumented and meant for internal use.
You can look at `spektral.datasets.qm9` for a template class that you can adapt to read your own SDF files

Cheers
