### ISSUE TITLE
How to run GATConv in batch mode?

### ISSUE THREAD

**Issue by taherhekmatfar** [danielegrattarola/spektral#227]
Hi,
Thanks a lot for your great package. 

As it says in the doc, GATConv supports batch mode. However, the basic GAT algorithm uses the full dataset to provide scores. 
So I was wondering how I could provide batches for GATConv?

**Comment by danielegrattarola** [comment]
Hi, 
you can use a BatchLoader to create batches of graphs or you can stack the adjacency and node feature matrices into higher-order tensors of shape `[batch, n_nodes, ...]`. The layer will deal with it automatically and will compute the scores independently for each graph. 

Cheers

**Comment by taherhekmatfar** [comment]
Hi, Thanks Daniele, 
The problem is that GAT algorithm needs the whole graph to compute the scores. So it is not possible to create batches of graphs. However, I will test the second solution you have provided. 
Thanks again

**Comment by danielegrattarola** [comment]
I am not sure we're on the same page regarding the definition of a batch.
In batch mode you are still passing the whole graph as input to the network, it's just that you have many "whole graphs" in a batch so that you can do things in parallel.
Does it make sense?

Cheers

**Comment by taherhekmatfar** [comment]
So if I get it right, If I have batchSize = 1 to calculate the scores of one node at each step, the GATConv will still get a complete adjacency and complete feature vector in batch mode, but the algorithm will run in parallel for each node or batch. Is it right?
Also, I tried the batch mode in your default example but I got an error. The code is as follows:

`def dataGen(loader):    
    while 1:
        yield(loader.__next__())`

`loader_tr = BatchLoader(dataset, batch_size=2)
model.fit(
    dataGen(loader_tr),
    steps_per_epoch=N/2,
    epochs=3
)`

And the error is: 
`
  File "\lib\site-packages\spektral\utils\misc.py", line 22, in pad_jagged_array
    output = np.zeros((target_len,) + target_shape, dtype=x[0].dtype)

TypeError: data type not understood`

I also tried to get data from loader as follows:
`for batch in loader:    yield(batch)`
But the error is still there. 
It seems there is a problem with the shape of inputs that loader returns and `(target_len,) + target_shape` is not a valid size to create numpy array.

**Comment by danielegrattarola** [comment]
Ok I think I understand where we disagree on definitions :)

There is no current way in Spektral to give as input to the network a subset of nodes from a **single** graph. 

When in the documentation you see "batch" mode, it refers to a setting where you have multiple graphs at the same time, and you want to create a batch of graphs (not nodes). 
Have a look [here](https://graphneural.network/data-modes/#batch-mode) to see what I mean. 

As for your crash, I am not sure what's going on. What dataset are you using and how was it created? Do you still get the crash if you use one of the datasets available in Spektral, like `spektral.datasets.TUDataset('PROTEINS')`?

Cheers

**Comment by taherhekmatfar** [comment]
Thanks, now I get that. So without batching on nodes I could not use GATConv in my algorithm.
I was trying to apply batching on Cora dataset. I think the error happens because the Cora is only one graph.
`dataset = Cora(normalize_x=True, transforms=[LayerPreprocess(GATConv), AdjToSpTensor()])`

**Comment by taherhekmatfar** [comment]
No, it's OK. 
Anyway, thanks a lot for your help and tips.

**Comment by danielegrattarola** [comment]
No problem! I'm closing the issue but feel free to comment if you need more help
