### ISSUE TITLE
Visualizing/retrieving attention coefficients in GraphAttention layer?

### ISSUE THREAD

**Issue by AI-Guru** [danielegrattarola/spektral#23]
Namaste!

Wow! spekral looks really great! I am currently investing some time to dig through the repository. I am amazed. Good work!

One thing: GraphAttention, as other attention layers, computes attention coefficients. Usually, these are visualized to learn a little more about attention during predictions.

Would it be feasible to make those available? Maybe a init parameter yield_attention_coefficients. If true, it would return both the output activation and the attention coefficients.

**Comment by danielegrattarola** [comment]
Hi!

Thanks for the positive feedback, I'm glad you like it!
That's actually something that I've had on my TODO list for a while now, I'll make sure to add this feature in one of the next commits. Stay tuned!

Cheers

**Comment by danielegrattarola** [comment]
This was added in commit ae928d22130c8c9b7d403ddac92930ce74e1f76f, and is already pushed to master. You will have to install from source, and then you can use `GraphAttention` with `return_attn_coef=True`. This will return a list of tensors after the updated node features:

```python
X_in = Input(shape=(F, ))
A_in = Input((N, ))
output, attn_coef = GraphAttention(channels, return_attn_coef=True)([X_in, A_in])
# attn_coef is a list of N x N tensors
```
