### ISSUE TITLE
Implementation of DiffusionConv is incorrect

### ISSUE THREAD

**Issue by Niklas2501** [danielegrattarola/spektral#243]
Hey, 
i was looking into using the DiffusionConv-Layer and have come across the following discrepancy between the documentation and the source code:

The documentation states that the "**Normalized adjacency** or attention coef. matrix" should be used and DiffusionConvolution.preprocess could be used for that. ([Link to doc.](https://graphneural.network/layers/convolution/#diffusionconv))

But when looking into the code the **gcn_filter() method is called** ([Link to source](https://github.com/danielegrattarola/spektral/blob/e99d5955a80eeae3c4605d8479f53aaa0ef5dbf2/spektral/layers/convolutional/diffusion_conv.py#L177)) (instead of normalized_laplacian() directly)

What is the reason for this?

Thanks!

**Comment by danielegrattarola** [comment]
The implementation is not correct, I will have to check the paper to make sure which is the correct one since I did not contribute this layer to the library. 
I think it's supposed to be `D_I ** -1 @ A + D_O ** -1 @  A.T` but I'll have to make sure.

thanks for noticing
