### ISSUE TITLE
[Feature] DATASET_FOLDER configurable?

### ISSUE THREAD

**Issue by krobasky** [danielegrattarola/spektral#247]
I wish the variable `datasets/util.py:DATASET_FOLDER` were configurable (maybe it is?) because the user directory (e.g., `~/`) often resides on a partition that's relatively small. In fact, on some of the systems I've used, filling up the home partition can block users from logging.

**Comment by danielegrattarola** [comment]
Hi, 

that's a great suggestion! I've implemented it and will push it soon to `develop`.

Cheers
Daniele
