### ISSUE TITLE
Calling predict() in a loop leaks memory

### ISSUE THREAD

**Issue by lukerm** [danielegrattarola/spektral#248]
Hi Daniele,

I have noticed when calling my Spektral model's `predict` function in a loop, the memory grows without bound. I thought I would ask here in case you know of any simple fixes to get around this. In the code below, I load up a small dataset, the Spektral model, and call `model.predict()` 1000 times in a loop (same dataset) and monitor the memory usage. The memory grows by over 11GB.
Here is the code I used:

```
import pandas as pd
import pickle

from memory_profiler import memory_usage

from spektral.data.dataset import Dataset
from spektral.data.loaders import DisjointLoader
from tensorflow.keras.models import load_model


scaler_file = "path/to/scaler.pkl"
model_file = "path/to/model.hdf5"


model = load_model(model_file)
with open(scaler_file, 'rb') as p:
    scaler = pickle.load(p)

df_feat, feature_names = get_feature_dataframe(index=0)  # custom function to load model-compatible data frame
df_feat[feature_names] = scaler.transform(df_feat[feature_names])


def predict_trials(n_trials):
    for _ in range(n_trials):
        # TreeDataset is a custom class, it subclasses Dataset
        tree_dataset = TreeDataset(data_frame=df_feat, feature_names=feature_names, root_included=False)
        data_loader = DisjointLoader(dataset=tree_dataset, batch_size=1, node_level=True, shuffle=False)

        _ = model.predict(data_loader.load(), steps=data_loader.steps_per_epoch)
        
        del tree_dataset.graphs
        del tree_dataset
        del data_loader


memory = memory_usage((predict_trials, (1000,), {}), 5, 600)
rolling_mean = pd.Series(memory).rolling(40).mean()
print(rolling_mean[~pd.isnull(rolling_mean)].reset_index(drop=True))
```

The memory summary is (grows by more than 11GB over 1000 iterations):

```
0      8126.309766
1      8376.003125
2      8653.546094
...
38    18689.153516
39    18970.774219
40    19231.113281
dtype: float64
```

The dataset size is not especially large:
```
print(df_feat[feature_names].shape)
(1040, 816)
```

Do you know why this is or if there are any tricks I can use to prevent the memory growing like this?

Thanks,
Luke

**Comment by danielegrattarola** [comment]
Hi,

my only guess is that since loader.load() creates a `tf.data.Dataset`, the memory management for that object is handled by Tensorflow in its backend and the GC is not being invoked correctly. 

This SO thread seems to be related: https://stackoverflow.com/questions/55211315/memory-leak-with-tf-data

You can try adding a call to `tf.keras.backend.clear_session()` right before the `del` calls.

Cheers

**Comment by lukerm** [comment]
Hi Daniele,

Success! Good suggestion, thank you! I changed the way I measure this a little bit from my original post, so it now performs the memory check several times (but still 1000 `predict()` calls in each one), i.e.:

```
n = 10
n_trials = 1000
for k in range(n):

    t0 = datetime.now()
    memory = memory_usage((predict_trials, (n_trials,), {}), 5, 600)
    t1 = datetime.now()
    total = (t1 - t0).total_seconds()
    print(f'increase: {round(max(memory) - min(memory))} in {round(total)}s')
```

This way it's more reliable. With my original `predict_trials` function, the memory seems to grow by about 4-5GB over 1000 calls:
```
increase: 5386 in 104s
increase: 4920 in 109s
increase: 5393 in 103s
increase: 4926 in 103s
increase: 5371 in 106s
increase: 4922 in 105s
increase: 5421 in 103s
increase: 4930 in 107s
increase: 5440 in 130s
increase: 4903 in 121s
```

You'll notice that I over-reported the first time (sorry!). I implemented a new version of the function with your suggested changes:


```
import gc
import tensorflow as tf

def predict_trials(n_trials):
    for _ in range(n_trials):
        tree_dataset = TreeDataset(data_frame=df_feat, feature_names=feature_names, root_included=False)
        data_loader = DisjointLoader(dataset=tree_dataset, batch_size=1, node_level=True, shuffle=False)

        _ = model.predict(data_loader.load(), steps=data_loader.steps_per_epoch)

        tf.keras.backend.clear_session()
        del tree_dataset.graphs
        del tree_dataset
        del data_loader
        gc.collect()
```

The great news is that this makes a significant difference to the memory growth, which is now less that 0.2GB over 1000 calls, which is much more useable!:

```
increase: 101 in 270s
increase: 82 in 267s
increase: 90 in 259s
increase: 125 in 256s
increase: 91 in 262s
increase: 115 in 257s
increase: 95 in 258s
increase: 107 in 258s
increase: 105 in 252s
increase: 75 in 255s
```

This works very well for me, but you will notice that it comes at a cost - there is about a 2.5x slow down to clear the memory each time. Maybe a better solution would to clear the memory every 10th time or something like that. 

Thanks again,
Luke

**Comment by danielegrattarola** [comment]
I understand the trouble, unfortunately much of the Loader interface is designed to work around the very strict limitations of the Keras fit loop, so it's up to the user to sort out these quirks.

Thanks for taking the time to benchmark, it will be useful for other users!

Cheers
Daniele
