### ISSUE TITLE
Notebooks for examples?

### ISSUE THREAD

**Issue by kmader** [danielegrattarola/spektral#25]
As a very visual learner, I thought it might be useful to have some more notebook-style examples with figures showing topology and outputs of intermediate layers, but I can appreciate they can unnecessarily bulk up a repository and make testing and versioning more difficult. I have made one [here](https://www.kaggle.com/kmader/mnist-graph-deep-learning), should I make a PR or a new repo?
![image](https://user-images.githubusercontent.com/116120/69956025-44b2b580-14ff-11ea-876d-d4969c19e891.png)

![image](https://user-images.githubusercontent.com/116120/69956062-572cef00-14ff-11ea-8e11-bc4865ce6106.png)

**Comment by danielegrattarola** [comment]
Hi, 

very nice work, I'm thinking that the easiest way would be to add a link to Kaggle in the [examples page](https://danielegrattarola.github.io/spektral/examples/) of the docs. 
This would simplify maintenance and allow you to make additions/improvements to the kernel without making pull requests. 

Would this work for you?

Best, 
Daniele
