### ISSUE TITLE
Examples for GraphSAGE?

### ISSUE THREAD

**Issue by RikonYu** [danielegrattarola/spektral#26]
Hello,
I'm trying to build a GraphSAGE model with spektral,I can find the graphsage conv layer amongst layers but I don't know how to use it, especially about the neighbor sampling part. And it seems that there is no graphsage example in examples folder either. Could you please provide an example using graphsage? Thanks!

**Comment by danielegrattarola** [comment]
Hi, 

You can start from any examples that use a GraphConv layer ([see here](https://github.com/danielegrattarola/spektral/blob/master/examples/node_classification_gcn.py)) and replace them with GraphSageConv layers. 
The usage is the same: 

```python
X_in = Input(shape=(F, ))
A_in = Input((N, ), sparse=True)
output = GraphSageConv(channels)([X_in, A_in])
```
If you are trying to replicate the GraphSage paper, the datasets are also available in `spektral.datasets.graphsage` ([see docs](https://danielegrattarola.github.io/spektral/datasets/graphsage/)).

Hope this helps
