### ISSUE TITLE
[Question] How to define the number of times the propagate function get called ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [danielegrattarola/spektral#268]
I am not quite grasping this concept … is every GNN layer considered to be a message passing step or can i specify the number of propagations happening in the same layer ?

**Comment by danielegrattarola** [comment]
Hi, 

each layer is usually intended as a single message passing step, you cannot (usually) specify the number of propagations steps.

Exceptions to this rule are ChebConv, ARMAConv, and APPNP, which all have a parameter that controls the number of hops used to compute the messages. 

Cheers
