### ISSUE TITLE
test_base_ops seems to be flaky when all seed-setting code is removed

### ISSUE THREAD

**Issue by melonwater211** [danielegrattarola/spektral#273]
### Introduction
`test_base_ops` in `tests/test_layers/test_ops.py` seems to be flaky when all seed-setting code (e.g. `np.random.seed(0)` or `tf.random.set_seed(0)`) is commented out. 

In commit 0e3c8545dc0e57719455eae1726736dc911662d9, `test_base_ops` failed 7 times (out of 5000 runs) compared to 0 of the times (out of 5000 runs) when no seed-setting code is removed or altered.   

### Motivation
Some tests can be flaky with high failure rates, but are not discovered when the seeds are set. We are trying to stabilize such tests.

### Environment
The tests were run using `pytest 6.2.2` in a `conda` environment with `Python 3.6.13`. The OS used was `Ubuntu 16.04`. 

### Possible Solutions
One possible solution to reduce flakiness is to make the tolerance of the assertions less strict.

Changing the tolerance from 1e-6 to 1e-5 reduced to flakiness to 0 failures (out of 5000 runs).

*This change did not increase the runtime of the test significantly.*

Please let us know if these solutions are feasible or if there are any other solutions that should be incorporated. We will be happy to raise a Pull Request to fix the tests and incorporate any feedback that you may have.

**Comment by danielegrattarola** [comment]
Thanks for opening this issue, indeed I have verified that atolerance of 1e-5 gives much more stable results. 

I have pushed a fix to `master` that implements your proposed change.

Cheers

**Comment by melonwater211** [comment]
We're glad the solution worked!
