### ISSUE TITLE
How to load tuple of graphs ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [danielegrattarola/spektral#279]
I am trying to implement a Siamese Graph Neural Network but i have a problem with graph loading, the `fit` function expects a graph or a list of graphs loaded from the `read` method in `Dataset` but the list of tuples i want to return doesn't have such data structure.

Is there any ideas to implement something like this ?

**Comment by danielegrattarola** [comment]
Hi, 

depending on how you want to structure the input, you might have to define a custom Loader and possibly a custom Dataset to use `model.fit` in this scenario. 

I think you're better off writing your own training loop and dealing with the batches manually. Datasets and Loaders are only there to help you, but if they become a burden you can always drop them.

Here's an example of how to write a custom training loop, you can edit the script for your needs/model: 

https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/general_gnn.py
