### ISSUE TITLE
DiffPool doesn't work with tuples

### ISSUE THREAD

**Issue by 9exa** [danielegrattarola/spektral#286]
BatchLoaders  returns data in the form of a tuple, so the ``build(self, input_shape)`` function in a DiffPool layer will also take in a tuple, if it is the first layer of a model. This will result in an assertion failure as the first line of ``build`` is:
``assert isinstance(input_shape, list)``.

I would recommend adding an
``or isinstance(input_shape, tuple)``
clause to the assert condition, for both DiffPool and other pooling layers that have this line.

Is there a reason why it expected only a list in the first place?

**Comment by danielegrattarola** [comment]
Thanks for noticing this, I have fixed it. 
You can install from source until I push a new version to pypi.

Cheers
