### ISSUE TITLE
Node classification with multiple graphs and batch loader

### ISSUE THREAD

**Issue by innekemayachita** [danielegrattarola/spektral#297]
Hello @danielegrattarola!

I want to train a node classification task and I have multiple graphs in my dataset, just like PPI dataset. I want to train on X number of graphs and predict on Y number of graphs. I might have > 1M nodes in total in my dataset. My questions are:

1. What's the pro and cons using Disjoint Loader and Batch Loader in this case? I'm thinking that using Disjoint Loader, all the graphs in the training set will be stored as 1 large sparse tensor and will that blow up the memory? I was interested in using Batch Loader and I saw this "Only graph-level labels are supported with this loader (i.e., labels are not zero-padded because they are assumed to have no "node" dimensions)". Does that mean I can't do node classification with Batch Loader?

2. Do you have examples on how to train node classification on multiple graphs, like using PPI dataset? I can only find the examples of using Citation Dataset which comprises of only 1 graph.

3. Building custom dataset means we will need to save the graph objects in a list like in [here](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/custom_dataset.py#L84). How can we handle this when we have a huge dataset? Will it blow up the memory? Alternatively, would it be possible to pass each graph object directly to the `.fit()` as an iterator instead of saving them in a list in an intermediate step? Thanks

**Comment by ratthachat** [comment]
> > What's the pro and cons using Disjoint Loader and Batch Loader in this case?

Hi, at first I could not think any pro of Batch over Disjoint; however, upon working on some complex problem like RNA node classification  where SOTA uses both conventional sequential models like RNN/Transformers/Conv1D together with GNNs, it seem that Disjoint mode which merge many sequences could not combine with these conventional layers

> > I was interested in using Batch Loader and I saw this "Only graph-level labels are supported with this loader (i.e., labels are not zero-padded because they are assumed to have no "node" dimensions)". Does that mean I can't do node classification with Batch Loader?
> 
> Yes, because the loader introduces virtual nodes.
> 
@danielegrattarola I think a user could fix this by using a custom loss to ignore (give zero scores to) the virtual nodes, while the target tensor will be needed to be padded as well.

**Comment by danielegrattarola** [comment]
You are right, this is a possible solution and it can probably be achieved with a custom loss + a [GraphMasking](https://graphneural.network/layers/base/#graphmasking) layer. 

I'll look into adding support for this to BatchLoader.

**Comment by Paul1086** [comment]
Hi @innekemayachita 
Did you able to figure out how to perform node classification with GCN from multiple graphs?
