### ISSUE TITLE
Two queation about the graph signal classification mnist

### ISSUE THREAD

**Issue by wenlongliao123** [danielegrattarola/spektral#300]
Dear Daniele,
        Hi. 
       Question 1: I ran your codes, which apply the GCN to classify MNIST,as shown in link1. However, I found the training speed be very slow and much slower than CNNs. In addition, after I ran your code for 1 hour, the accuracy rate was only 30%. The accuracy of the CNN classifier MNIST is generally greater than 90%.I wonder if there is something wrong with your code somewhere?Here is my training process:
Train loss: 2.1448, acc: 0.2223 | Valid loss: 1.9611, acc: 0.2767 | Test loss: 1.9513, acc: 0.2693
Train loss: 1.9385, acc: 0.2716 | Valid loss: 1.9141, acc: 0.2909 | Test loss: 1.8939, acc: 0.2936
Train loss: 1.8445, acc: 0.3009 | Valid loss: 1.8051, acc: 0.2990 | Test loss: 1.7999, acc: 0.2984
Train loss: 1.8317, acc: 0.3050 | Valid loss: 1.7895, acc: 0.3183 | Test loss: 1.7767, acc: 0.3118
Train loss: 1.8194, acc: 0.3092 | Valid loss: 1.7943, acc: 0.3066 | Test loss: 1.7767, acc: 0.3118
Train loss: 1.8123, acc: 0.3137 | Valid loss: 1.8066, acc: 0.3116 | Test loss: 1.7767, acc: 0.3118
Train loss: 1.8054, acc: 0.3166 | Valid loss: 1.8969, acc: 0.2865 | Test loss: 1.7767, acc: 0.3118
Train loss: 1.8042, acc: 0.3149 | Valid loss: 1.7812, acc: 0.3177 | Test loss: 1.7741, acc: 0.3128
Train loss: 1.7989, acc: 0.3176 | Valid loss: 1.8063, acc: 0.3121 | Test loss: 1.7741, acc: 0.3128
Train loss: 1.8002, acc: 0.3153 | Valid loss: 1.7925, acc: 0.3128 | Test loss: 1.7741, acc: 0.3128
Train loss: 1.7964, acc: 0.3163 | Valid loss: 1.8003, acc: 0.3059 | Test loss: 1.7741, acc: 0.3128
Train loss: 1.7957, acc: 0.3190 | Valid loss: 1.7761, acc: 0.3190 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7954, acc: 0.3185 | Valid loss: 1.7888, acc: 0.3163 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7942, acc: 0.3180 | Valid loss: 1.7941, acc: 0.3166 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7943, acc: 0.3177 | Valid loss: 1.7796, acc: 0.3193 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7905, acc: 0.3210 | Valid loss: 1.7824, acc: 0.3181 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7921, acc: 0.3193 | Valid loss: 1.8299, acc: 0.3133 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7889, acc: 0.3223 | Valid loss: 1.8004, acc: 0.3155 | Test loss: 1.7672, acc: 0.3179
Train loss: 1.7882, acc: 0.3212 | Valid loss: 1.7747, acc: 0.3232 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7907, acc: 0.3208 | Valid loss: 1.7892, acc: 0.3203 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7899, acc: 0.3180 | Valid loss: 1.7894, acc: 0.3197 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7896, acc: 0.3193 | Valid loss: 1.7798, acc: 0.3160 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7888, acc: 0.3190 | Valid loss: 1.7823, acc: 0.3190 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7876, acc: 0.3209 | Valid loss: 1.7903, acc: 0.3112 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7904, acc: 0.3199 | Valid loss: 1.8080, acc: 0.3131 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7879, acc: 0.3202 | Valid loss: 1.8123, acc: 0.3101 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7864, acc: 0.3220 | Valid loss: 1.7803, acc: 0.3162 | Test loss: 1.7615, acc: 0.3241
Train loss: 1.7865, acc: 0.3222 | Valid loss: 1.8200, acc: 0.3065 | Test loss: 1.7615, acc: 0.3241
Early stopping
         Question 2:  In my view, when we construct the adjacency matrix matrix A for each image from MNIST, the input is a 28*28 image. Each pixel can be regarded as a node, and a image includes 784 pixels. Therefore, the size of the adjacency matrix matrix A of each image is 784*784. In general, when we construct the adjacency matrix matrix for each image from MNIST, we should use the image as inputs. However, I noticed that you didn't use the data from the picture when constructing the adjacency matrix, you used random numbers to construct the adjacency matrix, as shown in the link2. The adjacency matrix constructed with random numbers is not correlated with the picture. Are you sure this construction is OK?
        Thank you so much for the code and the help.

link1:   https://github.com/danielegrattarola/spektral/blob/master/examples/other/graph_signal_classification_mnist.py
link2:   https://github.com/danielegrattarola/spektral/blob/master/spektral/datasets/mnist.py

**Comment by danielegrattarola** [comment]
Hi, 

1. That architecture is probably not the best choice for classifying mnist, I haven't really tuned it. It's just there to show how to train a model in mixed mode. However, 30% looks fairly low as accuracy, so I'll double check to see what's going on (I suspect that the sum-pooling readout is throwing away too much information, maybe a typical flattening will work better)

2. The grid is statically defined, it does not depend on the pixels. It's just a regular grid on top of which you put the image data. There should be no randomness in the construction unless you set `p_flip > 0` 

I'll update you on the architecture as soon as possible.

Cheers

**Comment by wenlongliao123** [comment]
Yes. when I replace the GlobalSumPool layer with Flatten layer. The accuracy is about 97.7%. Thanks for your answer. This library is very useful. If I write papers using Spektral, I will cite your paper. Thanks

**Comment by danielegrattarola** [comment]
@firqaaa yes, `Flatten` is a Keras layer but it only makes sense to use it when working with images like in the original issue. 
Otherwise, the equivalent operations for graphs are found in `spektral.layers.global_pool`

**Comment by danielegrattarola** [comment]
This is a problem with the inputs, not the readout. 
Can you post your model definition?
