### ISSUE TITLE
Is there a way to make the feature of a node a tensor instead of a vector?

### ISSUE THREAD

**Issue by lhcezx** [danielegrattarola/spektral#301]
Hi, 

I have a question about features on nodes, does n_feature have to be only one scalar? Can we have, for example, n_feature = (m,n) where m and n are both scalars respectively?

**Comment by danielegrattarola** [comment]
Hi, 

unfortunately this is not currently supported by Spektral, all layers assume that the features are vectors. 

Sorry

**Comment by lhcezx** [comment]
okay thx
