### ISSUE TITLE
GlobalAttnSumPool is calculating softmax over all samples in batch in disjoint mode.

### ISSUE THREAD

**Issue by MatejHl** [danielegrattarola/spektral#302]
Hello,

first of all, this a great library and thanks for this great work!

I noticed that [GlobalAttnSumPool](https://github.com/danielegrattarola/spektral/blob/master/spektral/layers/pooling/global_pool.py#L254) is performing softmax over all nodes in the graph even between disjoint subgraphs in disjoint mode.
Attention coefficients are calculated as
```
attn_coeff = K.dot(X, self.attn_kernel)
attn_coeff = K.squeeze(attn_coeff, -1)
attn_coeff = K.softmax(attn_coeff)
```
and if I understand correctly the softmax here is performed over all nodes in the graph. But this means that in disjoint mode **we are mixing together information from different samples in batch**. Then for disjoint mode graph we have segment sum that is cutting graph back into samples but this is already working with incorrect weights:
```
else:
    output = attn_coeff[:, None] * X
    output = tf.math.segment_sum(output, I)
```
From my understanding we want that GlobalAttnSumPool for disjoint mode is getting softmax weights per subgraph and not the whole graph. Just as a check I would expect that something like this `tf.math.segment_sum(attn_coeff, I)` returns a vector of ones.

PS: Unfortunately I'm not able to construct some minimalistic example, I'll try to create one if I have some spare time. But I printed out intermediate values in my model that I'm developing and indeed the result of `tf.math.segment_sum(attn_coeff, I)` is not a vector of ones.

**Comment by danielegrattarola** [comment]
Nice catch, that's 100% a bug. 
I should be able to fix it pretty easily, I'll update the issue once it's done. 

Thanks

**Comment by danielegrattarola** [comment]
Update: should be fixed, running `tf.math.segment_sum(attn_coeff, I)` returns a vector of 1s now. 

Can you verify that it works for you as well, by installing from source from the `develop` branch?

Thanks

**Comment by MatejHl** [comment]
Hi @danielegrattarola 

I tested it as well and it seems everything is working as expected. Nice work!

I'm closing the issue and thanks for the fast response and the fix.

Best,
      Matej
