### ISSUE TITLE
Citations

### ISSUE THREAD

**Issue by jparr721** [danielegrattarola/spektral#324]
Hello!

I am planning to publish a paper soon that includes the usage of this library. I have noticed with other libraries that there is typically a section in the github repository with the BibTeX citation. I noticed that this is not the case for this library, do you have something I can use? I'd like to give credit for all of your excellent work on this system.

**Comment by danielegrattarola** [comment]
Hi,

You can cite the Spektral paper! There is an ICML workshop version and a journal version, either is fine. Here's a Bibtex:

```
@article{grattarola2021graph,
  title={Graph neural networks in Tensorflow and Keras with Spektral},
  author={Grattarola, Daniele and Alippi, Cesare},
  journal={IEEE Computational Intelligence Magazine},
  year={2021}
}
```

**Comment by jparr721** [comment]
Thank you!
