### ISSUE TITLE
Correct use of GraphMasking and BatchLoader

### ISSUE THREAD

**Issue by ratthachat** [danielegrattarola/spektral#329]
Hi @danielegrattarola, 

I saw the example of `GraphMasking` in the `qm9_ecc_batch.py` where the network is defined :

```
class Net(Model):

    def call(self, inputs):
        x, a, e = inputs
        x = self.masking(x)
        x = self.conv1([x, a, e])
        x = self.conv2([x, a, e])
        output = self.global_pool(x)
        output = self.dense(output)

        return output
```

However, upon seeing the code of `GraphMasking`, it simply removes the mask attribute from `x` and not propagate the `mask` (not use `compute_mask` at all)

```
class GraphMasking(Layer):

 def call(self, inputs, **kwargs):
        # Remove mask from features
        if isinstance(inputs, list):
            inputs[0] = inputs[0][..., :-1]
        else:
            inputs = inputs[..., :-1]

        return inputs
```

Also, I see the `call()` method in a layer like `GCNConv` should recieve  `mask` as input, but there is no use of  `mask`  argument in `Net(Model)` ->` x = self.conv1([x, a, e]) ` example above.

----------------

## Correct use?
In my understanding, we should modify the `GraphMasking` to return both `mask` and mask-removed features, and then propagate the `mask` to below layers like this?

```
class Net(Model):
    def call(self, inputs):
        x, a, e = inputs
        x, mask = self.masking(x)
        x = self.conv1([x, a, e], mask=mask)
        x = self.conv2([x, a, e], mask=mask)
        output = self.global_pool(x)
        output = self.dense(output)

        return output
```
(so we should modify `GraphMasking.call()` to have also invoked `compute_mask `and return it )

Not sure if I understand this correctly, and appreciate any ideas. Thanks so much for your great library !!

**Comment by ratthachat** [comment]
It's a shame that I just found out how to use mask in keras :
https://colab.research.google.com/github/keras-team/keras-io/blob/master/guides/ipynb/understanding_masking_and_padding.ipynb#scrollTo=gUkoGLAAIDD1&uniqifier=1

So closing the issue for now :)

**Comment by danielegrattarola** [comment]
Glad you solved it, indeed it's all done automatically by Keras
Cheers
