### ISSUE TITLE
Question about Using GCNConv as a Feature Extractor

### ISSUE THREAD

**Issue by Zebin-Li** [danielegrattarola/spektral#331]
To whom it may concern,

I was trying to use GCNconv layer as a feature extractor and my issue is I can only perform 1 GCNConv layer. When I wanted to perform 2 GCNConv layers, there was an error that occurred and my code looks as follows:
```
loader2 = PackedBatchLoader(data1, batch_size=1, shuffle=False)
feat = []
labs = []

class MyFirstGNN1(Model):

    def __init__(self):
        super().__init__()
        self.graph_conv1 = GCNConv(256, 'relu')
        self.pool1 = GlobalSumPool()
        self.graph_conv2 = GCNConv(128, 'relu')
        self.pool2 = GlobalSumPool()

    def call(self, inputs):
        out = self.graph_conv1(inputs)
        out = self.pool1(out)
        out = self.graph_conv2(out)
        out = self.pool2(out)
        return out

model = MyFirstGNN1()

for i in range(num_graph):
    inputs2, target2 = loader2.__next__()
    feat.append(model(inputs2))
    labs.append(target2)
```
And the error is:

> Traceback (most recent call last):
  File "<input>", line 28, in <module>
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "<input>", line 19, in call
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\keras\engine\base_layer.py", line 1030, in __call__
    self._maybe_build(inputs)
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\keras\engine\base_layer.py", line 2659, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\lizeb\Box\research projects\Multiclass RAL\venv\lib\site-packages\spektral\layers\convolutional\gcn_conv.py", line 79, in build
    input_dim = input_shape[0][-1]
TypeError: 'int' object is not subscriptable

I am not sure where is the problem with the "input_shape". Could you please give me some hints? Thank you very much!

Best Regards,
Zebin Li

**Comment by danielegrattarola** [comment]
Hi, 

there are at least two problems with the model: 

1. `GlobalSumPool` returns a single vector fby summing up the node features, you can't do convolution on its output. You typically call it only once after you are done with graph convolutions in a model. 
2. When you are calling the second convolution, you are not passing the adjacency matrix as input. 

[Here's an example](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/tud_mincut.py) that you can use as a template. It also includes pooling, which I assume is what you wanted to do here. 

Cheers

**Comment by Zebin-Li** [comment]
Hi @danielegrattarola,

Thank you very much for your quick response and help!

Best Regards,
Zebin Li
