### ISSUE TITLE
Bug in deserialize_scatter function

### ISSUE THREAD

**Issue by lucasfarndale** [danielegrattarola/spektral#347]
I think the implementation of [deserialize_scatter](https://github.com/danielegrattarola/spektral/blob/4aaaff58e8d4f83efa81a3b66c5999216bd0f8e9/spektral/layers/ops/scatter.py#L216-228) is incorrect. The [`else` statement in line 220](https://github.com/danielegrattarola/spektral/blob/4aaaff58e8d4f83efa81a3b66c5999216bd0f8e9/spektral/layers/ops/scatter.py#L220) has an extra indent so if the input is not a string it does not progress to check if `callable`.

Currently it is implemented as
```
def deserialize_scatter(scatter):
    if isinstance(scatter, str):
        if scatter in OP_DICT:
            return OP_DICT[scatter]
        else:
            if callable(scatter):
                return scatter
            else:
                raise ValueError(
                    "scatter must be callable or string in: {}.".format(
                        list(OP_DICT.keys())
                    )
                )
```
and could be fixed by
```
def deserialize_scatter(scatter):
    if isinstance(scatter, str):
        if scatter in OP_DICT:
            return OP_DICT[scatter]
    else:
        if callable(scatter):
            return scatter
        else:
            raise ValueError(
                "scatter must be callable or string in: {}.".format(
                    list(OP_DICT.keys())
                )
            )
```

I've never raised an issue or pull request before so couldn't work out how to add the fix myself sorry.

**Comment by danielegrattarola** [comment]
Thanks for noticing this, I have fixed it!
