### ISSUE TITLE
Questions About  GraphConvSkip 

### ISSUE THREAD

**Issue by wyzhangyuhan** [danielegrattarola/spektral#348]
When I was studying the code of "Spectral Clustering with Graph Neural Networks for Graph Pooling", I found it used `GraphConvSkip` through `from spektral.layers.convolutional import GraphConvSkip`. But when I actually run it on Colab, I get an import failure. As follows:
```
ImportError                               Traceback (most recent call last)
[<ipython-input-34-6f55ef6cfe35>](https://localhost:8080/#) in <module>()
----> 1 from spektral.layers.convolutional import GraphConvSkip

ImportError: cannot import name 'GraphConvSkip' from 'spektral.layers.convolutional'
```

And after reading the Spektral documentation, there is no information about this class, or alternative solutions. So I wanted to ask if this class has been replaced or updated, and how can I change it so that the functionality doesn't change?

**Comment by danielegrattarola** [comment]
`GraphConvSkip` is the old name of `[GCSConv](https://graphneural.network/layers/convolution/#gcsconv)`.
The functionality hasn't changed, only the name.

**Comment by wyzhangyuhan** [comment]
> 
In addition, when I run the `Segmentation.py` provided in the paper mentioned earlier, I get the following error when calling `MincutPool`:

```
ValueError                                Traceback (most recent call last)
[<ipython-input-42-d2dfbfcd6d91>](https://localhost:8080/#) in <module>()
     37     '''
     38 
---> 39     pool1, adj1, seg1, C = MinCutPool(n_clust, activation=ACTIV, h=H_)([X_in, A_in, S_in], _)
     40 
     41     model = Model([X_in, A_in, S_in], [pool1, seg1])

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    697       except Exception as e:  # pylint:disable=broad-except
    698         if hasattr(e, 'ag_error_metadata'):
--> 699           raise e.ag_error_metadata.to_exception(e)
    700         else:
    701           raise

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/spektral/layers/pooling/mincut_pool.py", line 125, in call  *
        X, A = inputs

    ValueError: too many values to unpack (expected 2)
```
My personal opinion seems to be that the input accepted by the class in Spektral is inconsistent with the input in the code from the above paper. After comparing pytorch_geo with Spektral, I found that Spektral  library only parses two inputs: X and A, while pytorch_geo  parses X, A, and S. Where X stands for feature, A stands for adjacency matrix, and S stands for Assignment clusters. 

This also makes me confused, and I wonder if you, as the author of this paper, could give me some guidance on how to solve this problem. I would be  very grateful for that. (*^_^*)

**Comment by danielegrattarola** [comment]
The problem is that you're trying to run code based on TensorFlow 1.15 and Spektral 0.1.2, as you can see on [the repo](https://github.com/FilippoMB/Spectral-Clustering-with-Graph-Neural-Networks-for-Graph-Pooling).
Since you're trying to use the current version of Spektral, you should update the code to Tensorflow >= 2.2 and to the current API of the library (which, as you error suggests, does not take `S_in` as input. 

The reason why the Torch Geometric implementation requires S to be given as input is that their implementation requires the matrix to be computed elsewhere, whereas the Spektral implementation computes the matrix inside the layer itself. 

Hope this helps
