### ISSUE TITLE
More efficient MutiHeadAttention implementation

### ISSUE THREAD

**Issue by cgarciae** [danielegrattarola/spektral#35]
I was looking at the `MultiHeadAttention` implementation from the BERT repo on `tensorflow/models` and saw they implement this operation without branching + concatenation. They use 2 tricks:

- They create a multi-head version of `Dense` 
- They use `tf.einsum` to do the varios dot products while taking into account the heads.

I can try to convert the current implementation to this possibly more efficient strategy on the `tf2` branch. 

Checkout this striped down implementation of MHA I created recently: [code](https://github.com/cgarciae/point-cloud-attention/blob/a415fd912e82ba5322a701f732f0699a0cb49a7d/training/transformer/attention.py#L366)

References:

1. [Attention Layer from BERT](https://github.com/tensorflow/models/blob/d4ef56b1bd664bb0fec1e314e20b80158f03e909/official/nlp/modeling/layers/attention.py#L30)
2. [Official Tensorflow Tutorial](https://www.tensorflow.org/tutorials/text/transformer)

**Comment by danielegrattarola** [comment]
Hi, 

if you want to give it a shot and find out that it's more efficient, then you're welcome to open a PR with this change!

Some things to keep in mind re the code you linked:

1. Currently, the GraphAttention layer supports single, mixed and batch mode. If you change the implementation, it should keep this functionality (maybe it's possible to create the einsum string dynamically?); 
2. If the performance improvement is not significant and the new code ends up being harder to understand or more convoluted, then it might be better to keep the current implementation as-is.

Send me an email if you want to talk about this, I can help with the development. 

Cheers, 
D

**Comment by cgarciae** [comment]
Hey, 

1. I think that if we use `einsum`'s special `...` symbol the same code would work for both cases.
2. Using `einsum` actually cleans the code quite a bit since you don't have to keep lists of variables for each head and iterate over all the heads in the forward pass, but requires you to understand what the `einsum` operation is doing which can be tricky. I expect `einsum` to be more performant as you add more heads.

BTW: Is it ok to use regular `tf` functions in the `develop` branch now that Tensorflow is the only backend?

**Comment by danielegrattarola** [comment]
TIL about `...` in TF's einsum, I only knew the numpy notation. This may be useful to rewrite the ECC layer as well. 

Let's give it a go and see how it comes out, if you open a PR I am happy to contribute. 

Also, yes, regular `tf` is fine in `develop`. I was trying to limit its use back when the project started, but now there's no point anymore.
