### ISSUE TITLE
Failure to define the specific shape of a graph when use keras.Input to describe the input of a model

### ISSUE THREAD

**Issue by zzzy0828** [danielegrattarola/spektral#354]
Hi! When I want to use graphs as inputs for a model, I can't define the specific shape of the graph. To be more concrete, the keras.Input(shape=()), I failed to describe the right shape of a graph and as a result I failed to compile the whole model.
Code:
input1 = Input(shape=(None, None))  # keras.layers.Input
output1 = GCNConv(channels=16, activation='relu')(input1)
...
TypeError: 'NoneType' object is not subscriptable
So how can I address this problem? Expecting for your answer, thank you!

**Comment by danielegrattarola** [comment]
Hi, 

GCNConv (an essentially all convolutional layers in Spektral) expects two inputs: an adjacency matrix and a node features 
matrix. 
Here you're only giving the adjacency matrix as input.

You can have a look at the documentation for more details: https://graphneural.network
Also, there are some examples to help you get started: https://graphneural.network/examples/

**Comment by danielegrattarola** [comment]
Yes, the error is happening because GCN expects two inputs but you're only passing one input (`input1`).
Here's an example that shows the correct way of creating a GNN layer in Spektral:

https://github.com/danielegrattarola/spektral/blob/master/examples/node_prediction/citation_cheby.py

**Comment by zzzy0828** [comment]
Debug successfully!Thank you very much!!!
