### ISSUE TITLE
Problem with model.predict when using a BatchLoader

### ISSUE THREAD

**Issue by FrancoCuevas444** [danielegrattarola/spektral#367]
Hi!

I'm experiencing an error when I try to use `model.predict` with a BatchLoader, and the dataset size is not divisible by the `batch_size`.

```
# Here I load the dataset, that has 20 elements
loader_te = BatchLoader(data_te, shuffle=False, batch_size=16) 

...

# This is how I call model.predict
y_pred = model.predict(loader_te.load(), steps=loader_te.steps_per_epoch)
```

This is the error I receive:

```
InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [1,16,1] vs. shape[1] = [1,4,1] [Op:ConcatV2] name: concat
```

Both `model.fit` and `model.evaluate` work fine no matter the dataset size. Also, if I use a dataset that has an amount of elements divisible by the batch size It works fine as well.

Any help would be appreciated! Maybe I'm missing something.

Thanks!

**Comment by danielegrattarola** [comment]
hi, 

Can you post the full stack trace?

Thanks

**Comment by FrancoCuevas444** [comment]
The example was very helpful! It worked fine and from that I was able to find a bug in my model's `call` function related to some code I had left when I was using a `DisjointLoader`. 

Thank you very much!
