### ISSUE TITLE
Passing additional data when creating dataset?

### ISSUE THREAD

**Issue by JunyanReplicant** [danielegrattarola/spektral#368]
Hi, 
I love this library, thx for your effort!
I'm not sure if I miss something, this should be a common problem but hasn't been mentioned in the documentation.

For my dataset, each sample has an adjacency matrix, node features, and **also some additional metadata,** as well as the label (target).

Ideally, I'd like to implement something like this:
```py
dataList = MyDataset( node_features ,adjacency_matrix, meta_data, target )
dataBatch = spektral.data.loaders.BatchLoader(dataList, mask=False, batch_size=32, epochs=None, shuffle=False, node_level=False)
```
dataBatch.x will be **size (batch, node_num, node_features )**
dataBatch.a will be **size (batch, node_num, node_num)**
dataBatch.meta_data will be **size (batch,)** with each element an object of the metadata e.g., {'id': 'abc', 'number': 123}, some internal name or other properties of this graph.

When I implement my custom Dataset, 

> dataList[0].meta

 shows correct results {'id':xxx}. However, once the data is loaded, the meta data is lost
```py
currentBatch = next(dataBatch)
inputs = dataBatch[0]
x = inputs[0]
a = inputs[1]
target = dataBatch[1]
```
There is no dataBatch[2] nor inputs[2], or inputs.meta; I now cannot access the meta property.

An example of this use case is: Each graph stands for a company, with nodes representing workers, node_features representing workers age, working hours, etc.... However, there is also company-level data, for example, meta_data{company_name, founding years, year profits}. This meta data (company level) is independent of nodes (workers)

Here is how I implement my custom dataset:

```py
   class MyDataset(spektral.data.Dataset):
        def __init__(self, node_feature, adjMat , target, metadata,  **kwargs):
           # node feature size is (n_samples, nodes, node_features)
           # adjMat size is (n_samples, nodes, nodes)
           #metadata size is (n_samples, ) each is an object
           # target size is (n_samples, ) each is a integer label (1-10), for a graph classification problem.
            self.adjMat = adjMat
            self.node_feature= node_feature
            self.meta= metadata
            self.target = target
            super().__init__(**kwargs)

        def read(self):
            output = []
            for i in range(len(self.metadata)):
                x = self.node_feature[i,:,:]
                a = self.adjMat[i,:,:]
                y = self.target[i]
                m = self.meta[i]
                output.append(
                    spektral.data.Graph(x = x, a = a, y = y, meta = m)
                )
            return output
```

A workaround might be appending this metadata into a (or x)? Though, currently, both my node_features and adjacency matrix are all numbers, adding this meta data might be making their structure complicated as meta data includes strings etc. 

Thank you for any help or suggestions!

**Comment by danielegrattarola** [comment]
This is not supported by Spektral, your best bet is to implement your own Loader to deal with the metadata manually. 
You can start from the source code of [DisjointLoader](https://github.com/danielegrattarola/spektral/blob/master/spektral/data/loaders.py#L243) and work from there. 

Cheers

**Comment by JunyanReplicant** [comment]
Thanks, I'll try
