### ISSUE TITLE
Clarifying usage of to_batch

### ISSUE THREAD

**Issue by nilamandal** [danielegrattarola/spektral#380]
Hello, I am hoping to clarify how the spektral.data.utils.to_batch function is meant to be used. I was attempting to add a Diffpool layer after a CrystalConv layer while experimenting with this package. CrystalConv is using a disjoint loader, but Diffpool requires a batch format. I am using the QM9 dataset for testing. I believed I could use to_batch to convert between the two as follows:

```
class HNet(Model):
    def __init__(self):
        super().__init__()
        self.embedding= Dense(64)
        self.conv1= CrystalConv()
        self.conv2= CrystalConv()
        self.conv3= CrystalConv()
        self.pool= DiffPool(k=3)

    def call(self, inputs):
        x, a, e, i = inputs
        x= self.embedding(x)
        x= self.conv1([x, a, e])
        x= self.conv2([x, a, e])
        x= self.conv3([x, a, e])

        x, a = to_batch(x_list=x, a_list=a)

        x, a= self.pool([x, a])
```

However running this results in the message:
```
  File "/Users/myname/opt/anaconda3/lib/python3.7/site-packages/spektral/utils/misc.py", line 20, in <genexpr>
    shp if shp != -1 else x[0].shape[j] for j, shp in enumerate(target_shape)
IndexError: Exception encountered when calling layer "h_net" (type HNet).
```

I did not find any examples in the current body of examples which use to_batch or related functions. As such I am wondering if I am using this method improperly, or if there is some other problem.

**Comment by danielegrattarola** [comment]
Hi,

`to_batch` is not meant to be used in a model like that, it's only for numpy/scipy arrays. 

Have a look at `Disjoint2Batch`: https://graphneural.network/layers/base/#disjoint2batch

**Comment by nilamandal** [comment]
Hello again,
Sorry to disturb. After some experimentation with Disjoint2Batch, I am concerned whether I am again using this method inappropriately, or if there is an error in line 76 of spektral.layers.ops.mode.py, disjoint_adjacency_to_batch:

```
spaced_i_nodes = I * max_n_nodes + relative_i_nodes
```
I am using it in this manner:
```
class HNet(Model):
    def __init__(self):
        super().__init__()
        self.embedding= Dense(64)
        self.conv1= CrystalConv()
        self.conv2= CrystalConv()
        self.conv3= CrystalConv()
        self.disjoint2batch= Disjoint2Batch()
        self.pool= DiffPool(k=3, return_selection=True)

    def call(self, inputs):
        x, a, e, i = inputs
        x= self.embedding(x)
        x= self.conv1([x, a, e])
        x= self.conv2([x, a, e])
        x= self.conv3([x, a, e])
        x, a= self.disjoint2batch([x, a, i])

        #print(x.shape)
        #print(a.shape)
        #x, a= self.pool([x, a])
        #print('pool')
        return x
```

Whatever way I try it, in examining the source code this line seems to be attempting to compute (tensor of length= nodes in batch) * (scalar= size of largest graph in batch) + (tensor of length= number of edges in the batch). This results in the error

```
Incompatible shapes: [3104] vs. [6086] [Op:AddV2]
```
(values specific in the case of the QM9 dataset with batch size= 256)

It appears to me that this tensor operation cannot occur unless the number of nodes is equal to the number of edges. Could you please clarify this usage?

**Comment by danielegrattarola** [comment]
You are right, that line cannot work. 
I have to review that whole layer because I remember it got merged as part of a PR but it might have slipped through the testing. 
Marking this as a bug, I will update you once I have time to fix it

**Comment by nilamandal** [comment]
It appears that for my particular application, commenting out spaced_i_nodes and using the variable i_nodes in its place in line 77 produces an appropriate batch of adjacency matrices. But I have not tested it exhaustively.

**Comment by danielegrattarola** [comment]
I have pushed a fix for this issue, `Disjoint2Batch` now doesn't crash anymore. 

@nilamandal note that your fix is not correct in general, have a look at the one I just pushed.
