### ISSUE TITLE
Tensorflow 2.1.0 and Keras 2.3

### ISSUE THREAD

**Issue by takanovcs** [danielegrattarola/spektral#39]
Which keras version we need to install to use spektral v0.3?

**Comment by cgarciae** [comment]
Spektral `0.3` uses `tf.keras` so you just need to install the latest tensorflow.

**Comment by danielegrattarola** [comment]
Yep, it only depends on TF2 now. 
I realized that 0.3.0 still had Keras listed as a dependency in `setup.py`, I've released a patch (0.3.1) to remove it completely.
