### ISSUE TITLE
Including example implementation of Simple Graph Convolution

### ISSUE THREAD

**Issue by Tiiiger** [danielegrattarola/spektral#4]
Thank you for providing a geometric learning package in Kera. 

In our recent paper (https://arxiv.org/pdf/1902.07153.pdf), we show that a linear model (Simple Graph Convolution, SGC) that is as effective as GCN while saving a lot of training time. We have our official implementation at https://github.com/Tiiiger/SGC. I would like to ask if there will be interests of including SGC as an example in spektral. I am happy to help with the implementation.

The huge computational benefit of SGC comes from precomputing the message passing step. I'd like to discuss with you how best/cleanest to implement this through spektral. Look forward to your comments.

**Comment by danielegrattarola** [comment]
Hi, 

I think that the cleanest way to do this would be to pre-compute the correct Laplacian and then using a GCN with softmax activation. 

```python
# Preprocessing operations
node_features = citation.preprocess_features(node_features)
fltr = localpooling_filter(adj)

# Pre-compute propagation
for i in range(K - 1):
    fltr = fltr.dot(fltr)

# Model definition
X_in = Input(shape=(F, ))
fltr_in = Input((N, ), sparse=True)
output = GraphConv(n_classes,
                   activation='softmax',
                   kernel_regularizer=l2(l2_reg),
                   use_bias=False)([X_in, fltr_in])

# Build model
model = Model(inputs=[X_in, fltr_in], outputs=output)
```

I've coded the example and I get up to 80.9 on Cora, I will push it in a minute. 

Best, 
Daniele
