### ISSUE TITLE
In the example about regression molecules disjoint, if i want to use this model in my study, could you tell me how to create I_in for my dataset? I don't unstand what is the input "I_in", thank you very much!

### ISSUE THREAD

**Issue by xiaolinpan** [danielegrattarola/spektral#41]

**Comment by danielegrattarola** [comment]
Hi, 

you can create`I` manually as a 1D vector of integers, starting from 0, where each entry associates a node to one graph in the batch. 
So if you have two graphs in a batch, one with 3 nodes and the other with 4, you will need a vector `I = [0, 0, 0, 1, 1, 1, 1]`.

There are also tools to do this automatically for you, see `spektral.utils.data.Batch`.
