### ISSUE TITLE
is it possible to get an entire graph embedding with GraphSage and node removal

### ISSUE THREAD

**Issue by amjass12** [danielegrattarola/spektral#411]
Hi, 

I am training a GraphSage model and was wondering, if it is possible to aggregate all node embeddings to generate 'one' entire embedding that represents the graph?

Also, can GraphSage be used to generate node embeddings not just for new unseen nodes, but also for node removal? Fro example, If i now remove all edges from node 'x', can i get an updated node representation embedding using the same model?

Many thanks!

**Comment by danielegrattarola** [comment]
Sorry for the late reply but for some reason I stopped receiving notifications.

>Is possible to aggregate all node embeddings to generate 'one' entire embedding that represents the graph?

Yes, check out global pooling: https://graphneural.network/layers/pooling/#global-pooling-layers

>can GraphSage be used to generate node embeddings not just for new unseen nodes, but also for node removal?

Yes, although if you are completely disconnecting the edges of one node the model might give weird/useless predictions for that node. If you want to completely remove a node, you should also remove its node features so that it is no longer part of the graph.

**Comment by amjass12** [comment]
Hi @danielegrattarola ,

thank you so much for your reply - as a follow up:  would a graph attention network also be well suited to this, and then take for example, the mean of the node embedding vectors in the weights matrix including after node removal?

I ask this, as I have been working with transformers, and think this would be more powerful at expressing neighbourhood attention - but the same question would be, can nodes be removed and then re-fed in to the GAT - I am guessing, by also removing node features associated with the new graph?

thank you!

**Comment by danielegrattarola** [comment]
It's definitely possible, GNNs don't care about the number of nodes in an input graph, but the performance/generalization will of course depend on the size of the graphs that the model sees during training.

**Comment by amjass12** [comment]
@danielegrattarola 

thank you so much - ok this is perfect, i know how to proceed.. 

last two questions:

To get the newest model weights with the node removed, i simply pass it in the NEW adjacency matrix with the node removed, and the updated node features to get updated embeddings yes?

Also, on your point about quality of training, is it possible to feed several graphs during train for a GAT instead of just one graph?

**Comment by danielegrattarola** [comment]
>To get the newest model weights with the node removed, i simply pass it in the NEW adjacency matrix with the node removed, and the updated node features to get updated embeddings yes?

Correct, although I'm not sure what you mean with "model weights". The weights don't change after training, and they don't depend on the input size (like in a CNN, the kernel always stays the same).

> Also, on your point about quality of training, is it possible to feed several graphs during train for a GAT instead of just one graph?

Yes, it's a good idea to read the getting started tutorial (https://graphneural.network/getting-started/) and the data modes tutorial (https://graphneural.network/data-modes/).
There's also a collection of examples that you can start from (https://graphneural.network/examples/)

**Comment by amjass12** [comment]
@danielegrattarola 

excellent thank you for the advice on multiple graphs - will get started with this . 

With graph attention networks, wont the embeddings for each gene change based on context changes as a result of node removals? I have tried this with preliminary checks and when i remove a node and pass in the new adj-matrix, the embeddings of the GAT-conv change slightly (presumably as a result of node removal... (the mean of all node embeddings i what i am taking, and it changes when nodes are removed) -  this is what i meant originally, hope this makes sense?

thanks!

**Comment by danielegrattarola** [comment]
Yes, the embeddings will change as a consequence of node removal because you have modified the network and therefore the way information is exchanged between nodes. Imagine if you removed from your network of friends that one person who likes to gossip... everyone would still basically know the same things, but maybe slightly less :)

**Comment by amjass12** [comment]
Hi @danielegrattarola,

thank you so much - yes this is perfect. So to clarify, last question! - To get the updated embeddings is the right approach to take them from the first GATConv layer? this is how i am doing it:

```
layer_name = 'gat_conv'#this is the first GATConv layer
intermediate_layer_model = tf.keras.Model(inputs=model.input,
                                      outputs=model.get_layer(layer_name).output)
```
new graph **with** node removed:
#remove node
`intermediate_layer_model ([updated_node_features, updated_adj_matrix])
returns embedding of number_nodes by embedding_dimension
`

the updated adj matrix now simply has zeros for all nodes at the node that has been removed. My second question is: would you also make node features for the node that has been removed all 0, in order to get a better idea of the new embedding with that node no longer present?

thank you!

**Comment by danielegrattarola** [comment]
If you want to remove a node, it's better to completely remove the corresponding row from the node features and the corresponding row and column from the adjacency matrix. 
I think it should work either way, but it's better to completely remove it to be sure.

**Comment by amjass12** [comment]
@danielegrattarola , 

Excellent thank you! And thank you for you all help and advice!
