### ISSUE TITLE
No gradient for the initial adjacency matrix with TopKPooling

### ISSUE THREAD

**Issue by lawl-dev** [danielegrattarola/spektral#421]
Hello,

I am implementing a wasserstein gan and use TopKPooling in the generator and critic. To satisfy the 1 lipschitz constraint I have to calculate the gradient penalty with respect to the input variables (x and a).

To do this I tape.watch x and a, get the gradient with respect to x and a.values and compute the penalty.

But If I use TopKPooling (I think pooling in general) the gradients with respect to a.values are None.

Why is that and any Idea how to overcome this issue?

thank you very much,

Maxim

**Comment by lawl-dev** [comment]
Here is an example

`
    pool = TopKPool(0.5)
    gcn = GeneralConv()

    with tf.GradientTape() as tape:
        tape.watch(x)
        tape.watch(a.values)

        x, a = pool((x, a))
        x = gcn((x, a))
    
    gradients = tape.gradient(x, [x, a.values])
    gradient_x, gradient_a = gradients
`

**Comment by lawl-dev** [comment]
Ok, I got it. In conv layers where a binary adjacency is used the values are not taken into account while calculating the results, only the indices.
My bad. Sorry for the inconvenience.

**Comment by danielegrattarola** [comment]
Hey, glad you figured it out already :D

But yeah, the gradient wrt the adjacency matrix is only calculabe for a few convolutional layers in Spektral, generally it is not even defined. 

Good luck with your GAN
Cheers
