### ISSUE TITLE
Dependency Issue on Mac M2 Pro

### ISSUE THREAD

**Issue by IliyanYakimov** [danielegrattarola/spektral#431]
Hello,

I get this error when I try to install spektral==1.2.0 :
_ERROR: Could not find a version that satisfies the requirement tensorflow>=2.2.0 (from spektral) (from versions: 2.13.0rc0)
ERROR: No matching distribution found for tensorflow>=2.2.0_

I'm using tensorflow 2.12.0 and keras 2.12.0

When i try to install any version of spektral, it first deletes keras 2.12.0 and then installs keras 2.2.5 and spektral 0.0.13

**Comment by danielegrattarola** [comment]
Can you try installing from source? This should be fixed in a recent commit

**Comment by IliyanYakimov** [comment]
Installation from source went well and it's working fine. 

Thanks.
