### ISSUE TITLE
Is it require to create an adjacency matrix?

### ISSUE THREAD

**Issue by senemaktas** [danielegrattarola/spektral#436]
Hello, 

I have created a graph dataset with my own dataset. And it is consist of **nodes and labels**. 
I do not see necessary to create an adjacency matrices for graphs (nodes consist of the features and 
I would like to see that model extract the features between those nodes in graph level way). That part is done. 

When i run **general gnn** model it is looking for adjacency matrices. **Is it require to create
 an adjacency matrix?** I tried giving it as **None**, but the result is the same.
Here is the error:
  File "C:\....\general_gnn.py", line 172, in call
    z = layer([out, a])
  File "C:\....\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\.....\general_conv.py", line 137, in call
    x, a, _ = self.get_inputs(inputs)
  File "C:\....\message_passing.py", line 183, in get_inputs
    **assert K.is_sparse(a), "A must be a SparseTensor"
AssertionError: A must be a SparseTensor**

Thanks for your time.

**Comment by danielegrattarola** [comment]
Short answer: yes, you need an adjacency matrix.
You can just make a fake adjacency matrix with self-loops only (`sp.eye`) or even all zeros, but at that point, I would question the use of a GNN at all and whether you should instead use a MLP.

Cheers

**Comment by senemaktas** [comment]
Yes exactly, I thought same thing and filled adj matrix with ones. I probably confused it with another parameter to define as None. I will try to find proper way to create the matrix. Thank you very much for your answer.
