### ISSUE TITLE
No unsupvervised loss in GraphSAGE convolution layer

### ISSUE THREAD

**Issue by hadirkhan10** [danielegrattarola/spektral#446]
In the paper, they have an unsupervised loss implemented. However, it is not implemented in the codebase.
```python
>> model.losses
>> []
```

**Comment by danielegrattarola** [comment]
Hi,
the layer implementation is distinct from the particular loss that one might want to optimize, so this is by design.
I'm happy to merge an example with the unsupervised loss if you want to make a PR.

Cheers
