### ISSUE TITLE
No unsupervised loss for GINConv

### ISSUE THREAD

**Issue by hadirkhan10** [danielegrattarola/spektral#447]
I tried the following example: [tud_gin](https://github.com/danielegrattarola/spektral/blob/master/examples/graph_prediction/tud_gin.py) which adds `model.losses` to the total loss. However `model.losses = []`

**Comment by danielegrattarola** [comment]
Most of the examples are just boilerplate code that are supposed to be copy-pasted to start new projects. That sum with `model.losses` is used to, eg, add l2 regularization or other things like that if one wants.
