### ISSUE TITLE
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType' with tensorflow 2.0 and latest spektral 

### ISSUE THREAD

**Issue by ktakanov** [danielegrattarola/spektral#45]
This issue not occur with tensorflow 1 

`
# Model definition
from spektral.layers import GraphConv, GraphSageConv
from spektral.layers import *
import tensorflow as tf

from tensorflow.keras.layers import  Convolution2D, Input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import *
from tensorflow.keras.callbacks import *
from tensorflow.keras import backend as K
from spektral.layers.ops import sp_matrix_to_sp_tensor
from tensorflow.keras.metrics import binary_accuracy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.initializers import RandomUniform

r = RandomUniform(minval=-1, maxval=1, seed=42)
activation='relu'

S = 2

X_in = Input(shape=(N, F))
A_in = Input(shape=(N, N))

M = 50
M2 = 10 
M3 = 5 

def access_column(arr,col):
  return arr[:,:,col]

def access_column_dims(arr,col):
  return K.expand_dims(arr[:,col],axis=1)

x_1 = Lambda(lambda x: access_column(x,0))(X_in)
e1 = Embedding(total_items, M2, embeddings_initializer=r)(x_1)
e1 = Reshape((M2,-1))(e1) 

x_2 = Lambda(lambda x: access_column(x,1))(X_in)
e2 = Embedding(total_categories, M2, embeddings_initializer=r)(x_2)
e2 = Reshape((M2,-1))(e2) 

e3 = Lambda(lambda x: access_column(x,2))(X_in) #items clicked
e3 = Dense(10, input_shape=(N,1))(e3)
e3 = Reshape((M2,-1))(e3)

e4 = Lambda(lambda x: access_column(x,3))(X_in) #dwelltime
e4 = Dense(10, input_shape=(N,1))(e4)
e4 = Reshape((M2,-1))(e4)

c = Concatenate(axis=-1)([e1, e2, e3, e4])

n_attn_heads = 8
n1 = 64
n2 = 64

l = GraphAttention(n1, activation='relu', attn_heads = n_attn_heads)([c, A_in]) # skip-connection
l = GraphAttention(n1, activation='relu', attn_heads = n_attn_heads)([l, A_in])
l = GlobalAttentionPool(n2)(l)

output = Dense(1, activation='sigmoid')(l)
model = Model(inputs=[X_in, A_in], outputs=output)

opt = Adam(lr=0.0001)

loss_f = 'binary_crossentropy'

model.compile(optimizer=opt, loss=loss_f, metrics=[f1_m, precision_m, recall_m])
model.summary()
`

Output:
`
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/init_ops_v2.py in _compute_fans(shape)
    733     receptive_field_size = 1.
    734     for dim in shape[:-2]:
--> 735       receptive_field_size *= dim
    736     fan_in = shape[-2] * receptive_field_size
    737     fan_out = shape[-1] * receptive_field_size

TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'
`
Please help :(

**Comment by danielegrattarola** [comment]
Hi, can you provide a runnable code snippet? This one does not run.
Also it would be great if you could post the full stack strace so that I can see which layer is causing the issue. 
Cheers
