### ISSUE TITLE
float adjacency matrix

### ISSUE THREAD

**Issue by envytails** [danielegrattarola/spektral#46]
Hi!
Is possibile to use an adjacency matrix of float values? Several studies uses weighted adjacency matrix (i.e. 0<=Adj<=1 instead of Adj in {0,1} values). Is spektral already ready for this kind of adjacency matrix or using float Adj matrix could lead to some run (or logical) error?

**Comment by danielegrattarola** [comment]
Hi, 

sure, you can use a weighted adjacency matrix. Several GNN methods require to compute some form of normalization of the adjacency matrix anyway, so it is common to have float inputs.

Cheers
