### ISSUE TITLE
The output of topkpooling

### ISSUE THREAD

**Issue by lhanappa** [danielegrattarola/spektral#48]
May I ask why the output of TopKpooling does have the dimension of [batch]? like "Reduced node features of shape ([batch], K, channels);"

**Comment by danielegrattarola** [comment]
The square brackets indicate that the batch dimension is optional, meaning that *if* you give it data in batch mode (`X.shape == (batch, n_nodes, n_features)` and `A.shape == (batch, n_nodes, n_nodes)`) then it will return a consistent array with a batch dimension.
