### ISSUE TITLE
Colab import error

### ISSUE THREAD

**Issue by cerlymarco** [danielegrattarola/spektral#50]
On Colab (tf 2.2.0) the installation is ok but the import gives an error: 

/usr/local/lib/python3.6/dist-packages/spektral/layers/base.py in <module>()
      4 from tensorflow.keras import backend as K
      5 from tensorflow.keras.layers import Layer
----> 6 from tensorflow_core.python.keras.utils import tf_utils

ModuleNotFoundError: No module named 'tensorflow_core'

**Comment by danielegrattarola** [comment]
Hi, I'm not sure why tensorflow_core would not be available on Colab. Does it work with TF 2.1?

Anyway, I have just pushed a fix that should solve this issue. You have to install from source for now, I will be releasing a new version to PyPi soon.

Cheers

**Comment by cerlymarco** [comment]
Hi, thanks, I've to force to install TF 2.1 while the default TF version on colab is 2.2.

I look forward to the release of a new version with Window compatibility!

Great job! 
Ciao
