### ISSUE TITLE
numpy_to_batch throws error on TU dataset

### ISSUE THREAD

**Issue by LeviBorodenko** [danielegrattarola/spektral#55]
Running the following code using the Spektral 0.5.0 throws an unexpected error:

```python
from spektral.datasets import tud
from spektral.utils import numpy_to_batch

A_list, X_list, y = tud.load_data('MUTAG', clean=True)
numpy_to_batch(X_list, A_list)
```
The ValueError it throws is: 
`ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (0,2)`

Try it out in [in collab](https://colab.research.google.com/drive/1ePkL5Nn6gSxATcKGJoHRGmRQwSW9I2-u?usp=sharing)

**Comment by danielegrattarola** [comment]
Nice catch!!
I will be pushing a fix in a minute and also releasing a patch on PyPi.  

Thanks!

**Comment by LeviBorodenko** [comment]
I believe it is caused by np.pad not being compatible with sparse.coo.coo_matrix :)

Cheers!

**Comment by danielegrattarola** [comment]
Yeah, that was exactly it!
It's up on PyPi and `master`, give it a go :D 

Cheers

**Comment by LeviBorodenko** [comment]
Works! perfect
