### ISSUE TITLE
Potential of a Batch2Disjoint layer and the future of modes

### ISSUE THREAD

**Issue by LeviBorodenko** [danielegrattarola/spektral#62]
Hi,

with the `Disjoint2Batch` layer committed, I was wondering if there is need for a `Batch2Disjoint` layer.
My idea is, to then fuse these two into a `ModeMatch` layer that can go between any two spektral layers and will (potentially automatically) convert the output of the first layer to match the needed mode of the second.

On the up side, this would allow all layers to communicate with each other and if build into the GraphConv/MessagePassing base class, it could remove some headaches from new users by allowing them to not care much about modes.

On the down side, this conversion would then be part of the model and not just the preprocessing, which could have noticeable effects on training and memory usage.

Do you think it is worth-while?

Best,
Levi

**Comment by danielegrattarola** [comment]
Hi Levi, 

I agree that this would be useful for new users, but I don't like the idea of changing the data in the backend like this. 
I think it's better if the mode is preserved from input to output, also to prevent unexpected performance hits. If users want to change modes, then it's better if they do it explicitly. 

Also for what concerns the Batch2Disjoint layer, I wouldn't spend effort on it. The modes system needs a bit of refactoring anyway, and is on my list of things to improve in the near future. 

All the best, 
Daniele
