### ISSUE TITLE
Error when feeding multi input 

### ISSUE THREAD

**Issue by mdshopon** [danielegrattarola/spektral#63]
I am training a Graph neural network with an auxiliary input layer. I am concatenating the layers. The model compiles perfectly. But when fitting the data into the model I am getting the following error. 

`ValueError: No data provided for "input_10". Need data for each key in: ['input_10', 'input_12']`

I have used an example from the example folder and modified it for multi input. 

`X_in = Input(shape=(1375, 3))`
`A_in = Input(tensor=sp_matrix_to_sp_tensor(adj_mat))`

`Feat_input = Input(shape=(55,8))`

`Feat_layer = Bidirectional(LSTM(32, return_sequences=True,),name='lstm_input')(Feat_input)`
`Feat_layer = Dense(512,activation='relu')(Feat_layer)`
`Feat_layer = Flatten()(Feat_layer)`

`graph_conv = GraphConvSkip(64,
                       activation='relu',
                       kernel_regularizer=l2(l2_reg),name='graph_input')([X_in, A_in])`

`graph_conv = Dropout(0.5)(graph_conv)`
`graph_conv = ChebConv(32,
                       activation='relu',
                       kernel_regularizer=l2(l2_reg))([graph_conv, A_in])`
`graph_conv = Dropout(0.5)(graph_conv)`
`graph_conv = GraphConvSkip(64,
                       activation='relu',
                       kernel_regularizer=l2(l2_reg))([graph_conv, A_in])`
`graph_conv = Dropout(0.5)(graph_conv)`
`graph_conv = ChebConv(32,
                       activation='relu',
                       kernel_regularizer=l2(l2_reg))([graph_conv, A_in])`

`flatten = Flatten()(graph_conv)`

`concatenated = concatenate([flatten, Feat_layer])  `

`fc = Dense(512, activation='relu')(concatenated)`
`fc = Dense(256, activation='relu')(fc)`
`output = Dense(n_out, activation='softmax')(fc)`

`model = Model(inputs={'graph_input':[X_in, A_in], 'lstm_input':Feat_input}, outputs=output)`
`optimizer = RMSprop(lr=learning_rate)`
`model.compile(optimizer=optimizer,
              loss='categorical_crossentropy',
              metrics=['acc'])`
`model.summary()`
`history = model.fit({'graph_input': [X_train], 'lstm_input': x_train_feat },
          y_train,
          batch_size=28,
          epochs=250,steps_per_epoch=10)`

**Comment by danielegrattarola** [comment]
Hi, 

it seems like Keras doesn't like the dictionary input format that you are using. 
Passing a fixed tensor as input is a bit old and hacky, and it's not really "stable" w.r.t. all features of Keras.  Anyway, I would first try to remove the input dictionary and pass everything in a list. It should work.

Best, 
Daniele

**Comment by danielegrattarola** [comment]
FYI the updated graph signal classification example should make it easier to define a custom model with fixed inputs, like the one you were trying to create. 
I realize several months have passed, but maybe it's still helpful.

I'm closing this issue anyway. 
Cheers
