### ISSUE TITLE
Error mask = -10e9 * (1.0 - A) on ./layers/convolutional/gat.py:179

### ISSUE THREAD

**Issue by imayachita** [danielegrattarola/spektral#66]
Hi Daniele,
I tried running the examples on node classification using GAT and I got following error:
``` TypeError: unsupported operand type(s) for -: 'float' and 'SparseTensor'```
on ```layers/convolutional/gat.py:179 call  *
        mask = -10e9 * (1.0 - A)```

Do you have any idea what caused this?
Thanks!

**Comment by danielegrattarola** [comment]
Hi, 

what version of the library causes this?
It should not happen in the latest releases, GAT should handle the situation automatically.

Have you tried installing from source the latest version?

All the best, 
Daniele
