### ISSUE TITLE
Implement of Relational GNN

### ISSUE THREAD

**Issue by gitlabspy** [danielegrattarola/spektral#67]
Hi Daniele,
Is R-GNN implemented in spektral?

**Comment by danielegrattarola** [comment]
If you are referring to https://arxiv.org/abs/1703.06103 then no, but the [Edge-Conditioned Convolution](https://graphneural.network/layers/convolution/#edgeconditionedconv) should be close enough.

Anyway, RGCN is definitely coming down the line, I have been adding new layers to the library recently.

Cheers
