### ISSUE TITLE
unable to import spektral

### ISSUE THREAD

**Issue by aliceblueberry** [danielegrattarola/spektral#71]
After successfully importing spektral, I was unable to import the package in code. when attempting to import tud, the program throws error `<AttributeError: 'DataFrame' object has no attribute 'Name'.>`

It looks like the problem was with the example dataset that spektral collects. I was using Anaconda Python 3.6, pip version 20.0.2, Spektral version 0.5.
![Screen Shot 2020-07-02 at 2 25 32 PM](https://user-images.githubusercontent.com/33659960/86401523-fa014380-bc6f-11ea-9add-f1a531b8fffc.png)

**Comment by danielegrattarola** [comment]
Hi, 

what version of Pandas are you using?
I cannot reproduce the problem using Pandas 0.25.3.

Cheers

**Comment by aliceblueberry** [comment]
I was using pd version 0.22.0. But anyway, just run a full update and the error seemed to have gone. Thanks though!

**Comment by danielegrattarola** [comment]
No problem, happy coding!

Cheers
