### ISSUE TITLE
Importing GraphConv hangs for a long time without internet!

### ISSUE THREAD

**Issue by drcege** [danielegrattarola/spektral#75]
In the absence of internet access, every run of the code gets stuck for nearly one minute. And I just imported the GraphConv module!

After a simple inspection, this seems to be related to datasets checking.
https://github.com/danielegrattarola/spektral/blob/4e9779ac05c29bd64c5cbb374852b2cf2dbcdb3b/spektral/datasets/tud.py#L19-L26

This is quite annoying. I think normally datasets should only be retrieved when needed. Or, the check may be performed in the background and cached when appropriate.

**Comment by danielegrattarola** [comment]
You are right, that piece of code was only supposed to be temporary and has already given me headaches. 
I've moved it to a function `available_datasets` now. 

Install from source for latest version that fixes the issue. 

Cheers
