### ISSUE TITLE
Spatially non-symmetric output from spatially symmetric input

### ISSUE THREAD

**Issue by davidxujiayang** [danielegrattarola/spektral#82]
Hi, 

Thanks for providing this library! I ran into a issue and not sure if it's my problem or something behind the scene. 

I trained a model with fully EdgeConditionedConv layers, which I thought should be providing spatially symmetric output if the input is spatially symmetric. By spatially symmetric, I mean that my graph is generated from a spatially uniformly meshed data, and the node features are symmetric in both x and y direction. The only edge feature is the spatial vector defined by the difference between coordinates of the nodes, which would also be symmetric.

I attached the graph and the input (top) vs output (bot) contours below. I apologize in advance if the description is not clear enough, any thoughts would be appreciated.

![graph](https://user-images.githubusercontent.com/24285886/89910821-b0850c00-dbbe-11ea-982e-1c09d1e170a4.png)

![pred_contour_300_700_4_c](https://user-images.githubusercontent.com/24285886/89910770-a4994a00-dbbe-11ea-99f1-313dce8d6355.png)

Best,

**Comment by danielegrattarola** [comment]
Hi, 

Your intuition is correct, the output should be symmetric as far as I can tell.

Can you share a minimal code example to reproduce the issue?

Cheers, 
Daniele

**Comment by davidxujiayang** [comment]
Hi Daniele,

Thanks for your reply! I attached the scripts to reproduce the issue. I did a lot of cleaning but it is still very unprofessional, apologize in advance for the inconvenience. 
To reproduce:
First you will need to run heat2d.py to generate data.
Then run npy_to_graph.py to generate graph
Then by running run_mpnn.py should reproduce a similar problem. I have made the training epochs and network size smaller than before to make the training faster.

Thanks again,
David
[reproduce_nonsymmetric.zip](https://github.com/danielegrattarola/spektral/files/5066877/reproduce_nonsymmetric.zip)

**Comment by danielegrattarola** [comment]
I did a smaller test with the following code: 

```python
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

from spektral.layers import EdgeConditionedConv
from spektral.layers import ops

# Create a grid
g = nx.generators.lattice.grid_2d_graph(4, 4)
a = nx.adj_matrix(g)
a = ops.sp_matrix_to_sp_tensor(a)

# Create symmetric node features
x = np.array([
        0, 0, 0, 0,
        0, 1, 1, 0,
        0, 1, 1, 0,
        0, 0, 0, 0
    ]).reshape(-1, 1).astype('f4')

# Create symmetric edge features
e = np.ones((48, 1))

# Create ECC layer
l = EdgeConditionedConv(5, activation='relu')

# Get output
o = l([x, a, e]).numpy()

#Plot
plt.subplot(1, 2, 1)
plt.imshow(x.reshape(4, 4))
plt.title('Input')
plt.subplot(1, 2, 2)
plt.imshow(o[:, 1].reshape(4, 4))  # Second column is non-zero in my case
plt.title('Output')
```

And it gives me the following output:

![Figure_1](https://user-images.githubusercontent.com/11634240/90114202-b0b61080-dd52-11ea-8329-17256536b51d.png)

Which, as expected is symmetric. 
I am not sure what the problem could be in your case, but I would start from checking that the data that you're feeding to the network is actually symmetric. 

Hope this helps.
Cheers

**Comment by davidxujiayang** [comment]
Thanks for the test and advice,

I checked my input and it is not exactly symmetic. That's my bad, sorry for the confusion and really appreciate the time you spent on the test.
