### ISSUE TITLE
Heterogeneous Graph

### ISSUE THREAD

**Issue by imayachita** [danielegrattarola/spektral#91]
Hi @danielegrattarola,
I am wondering if the current version of Spektral supports heterogeneous graph (for node / graph / relation classification) ?

Thanks!

**Comment by danielegrattarola** [comment]
Hi, 

unfortunately there is no support for heterogeneous graphs as of now. 
This is something that I plan to implement down the line but I have been really swamped with work lately. 

Cheers!

**Comment by imayachita** [comment]
Thanks!
