### ISSUE TITLE
Node Classification in Disjoint Mode - ValueError "all inputs to the Python function must be convertible to tensors"

### ISSUE THREAD

**Issue by Shakesbeery** [danielegrattarola/spektral#94]
Is it possible to create a graph network that predicts node classes on variable size graphs? I'm following the BDGC and QM9 examples almost exactly, but my `y_train` and `y_test` are a list of nodes and their one-hot classes. So the first graph may have 50 nodes and 2 attributes , but the second graph may have 160 nodes with 2 attributes. The y_train values in these cases are of shape (50, 20) and (160, 20). 

When I try to run training on this dataset, I get: `ValueError: When input_signature is provided, all inputs to the Python function must be convertible to tensors`

I assume this is due to the inability to represent variable size matrices as a single tensor. I've tried using only batch size 1, but with no luck. Am I missing a function, utility or process that permits node classification in disjoint mode?

**Comment by danielegrattarola** [comment]
Hi, 

can you check your Tensorflow version?
Do the examples run on your machine if you don't change anything?

Cheers

**Comment by Shakesbeery** [comment]
Tensorflow: `2.2.0`

Yeah, I can get the examples running fine if I don't change anything. If I use a fixed-size, randomly generated `y_train`, the code will also work. So the problem seems to be with the variable-sized output targets.

**Comment by danielegrattarola** [comment]
I have misread the original issue. It seems like you are trying to do node-level classification, is that correct? In that case, the BDGC and QM9 must be adapted to work correctly. 

In short: 
1. remove the global pooling layer from the network
2. stack your targets in a single matrix of shape `(50 + 160, 20)`

If you stack your graphs in disjoint mode with adjacency matrix of shape `(210, 210)` and node features of shape `(210, 2)`, you will get 210 outputs (if you don't use the global pooling layer).

Cheers

**Comment by Shakesbeery** [comment]
Bingo! Stacking was the step I was missing. Works like a charm now. Thanks so much for your insights and for the whole Spektral package. :)

**Comment by danielegrattarola** [comment]
Nice! Good luck with your project!
(I'm closing the issue since it is solved)

Cheers
