### ISSUE TITLE
About updates

### ISSUE THREAD

**Issue by arxidinakbar** [danielegrattarola/spektral#95]
First of all, much appreciation to this library and wonderful jobs .
And found this interesting research named 'Attpool', which contributes remarkable effort to GCN study.
I just wondering would this work(also other GNN works) updating to the library in future?

**Comment by danielegrattarola** [comment]
Hi, 

thanks for the nice feedback. 

Yes, I have planned to add new layers (especially pooling) and I will definitely consider AttPool. I haven't had a lot of time to work on new features, but they are coming.
Stay tuned. 

Cheers

**Comment by arxidinakbar** [comment]
@danielegrattarola Hi, thank you for the quick reply.
I am happy to do tiny effort to this sphere.
I'm look forward to the newest update then.
Again, appreciate, wish you all good.  

Good luck
