### ISSUE TITLE
Any way to implement multi-dimensional graph classification?

### ISSUE THREAD

**Issue by thehemen** [danielegrattarola/spektral#97]
Hello.
I'd like to learn is it possible to classify graphs with edges connecting more than two nodes?
For example, if we have a classical graph, we use an adjacency matrix like (N, N) and edge features like (N, N, S).
But if we want to use connections of, say, three nodes, it will look like (N, N, N) and (N, N, N, S).
Is it feasible now?

**Comment by danielegrattarola** [comment]
Hi, 

there is no support for hypergraphs in Spektral for now, although it's probably coming eventually.

Cheers
